const CharArt = (() => {
  'use strict';

  // ===========================================================================
  // CharArt - procedurally assembled 16x16 top-down character sprites
  // (16-bit era chibi style: big heads, 1px dark outline, light from top-left).
  //
  //   CharArt.get(kind, dir, frame) -> HTMLCanvasElement (16x16, transparent bg)
  //       dir:   'down' | 'left' | 'up' | 'right'   (anything else -> 'down')
  //       frame: 0 | 1 walk cycle (any integer is taken modulo 2)
  //       unknown kind -> the 'man' sprite.  Never throws.  Results are cached,
  //       so the same canvas object is returned for the same arguments.
  //   CharArt.kinds -> array of all kind ids
  //
  // Every pixel is either fully opaque or fully transparent.  Adult sprites
  // stand with feet on row 15; 'boy' and 'girl' are drawn smaller (head starts
  // at row 3 instead of row 1); 'ghost' floats (bobs 1px between frames) and
  // 'coffin' hops 1px on frame 1.
  //
  // How the art is built: small ASCII templates (one char per pixel) are
  // merged into "parts" (e.g. body, head, held item); each part is outlined
  // automatically (4-neighbour, colour OUTLINE) and parts are composited in
  // order, so e.g. a head always gets a clean chin line over the body.
  // 'right' is the horizontal mirror of 'left'.
  //
  // Template letters (resolved per kind through its palette):
  //   k outline/eyes   S s L skin (base/shadow/light)   H h I hair
  //   A a Y main cloth (base/shadow/highlight)          B b secondary cloth
  //   C belt/trim   D d shoes   E e F f headwear   G g gold   M m n metal
  //   W w white   R r red/cape   T t wood   V v apron/vest/overlay
  //   others (J X x N O P p Q) are kind-specific accents.
  // ===========================================================================

  const OUTLINE = '#181018';

  // ---------------------------------------------------------------------------
  // Template helpers.  A template is an array of 16 strings of 16 chars.
  // '.' = leave as is, '_' = erase (within the current part), 'k' = outline
  // colour, anything else = palette key.  A line '@N' moves to row N.
  // ---------------------------------------------------------------------------
  const EMPTY_ROW = '................';
  const badTemplates = [];
  function tpl(src) {
    const rows = new Array(16).fill(EMPTY_ROW);
    let y = 0;
    for (const raw of src.split('\n')) {
      const line = raw.trim();
      if (!line) continue;
      if (line[0] === '@') { y = parseInt(line.slice(1), 10); continue; }
      if (line.length !== 16) badTemplates.push('row ' + y + ' len ' + line.length + ': ' + line);
      if (y > 15) break;
      rows[y] = (line + EMPTY_ROW).slice(0, 16);
      y++;
    }
    return rows;
  }
  function mirror(t) { return t.map(r => r.split('').reverse().join('')); }
  function shift(t, dx, dy) {
    if (!dx && !dy) return t;
    const out = new Array(16).fill(EMPTY_ROW);
    for (let y = 0; y < 16; y++) {
      const sy = y - dy;
      if (sy < 0 || sy > 15) continue;
      let row = '';
      for (let x = 0; x < 16; x++) {
        const sx = x - dx;
        row += sx >= 0 && sx < 16 ? t[sy][sx] : '.';
      }
      out[y] = row;
    }
    return out;
  }

  // ---------------------------------------------------------------------------
  // Rendering: a sprite is a list of parts; each part is a list of templates
  // merged in order, then auto-outlined (4-neighbour) and composited.
  // ---------------------------------------------------------------------------
  function renderParts(parts, pal) {
    const out = new Array(256).fill(null);
    for (const part of parts) {
      const g = new Array(256).fill(null);
      for (const t of part.t) {
        for (let y = 0; y < 16; y++) {
          const row = t[y];
          for (let x = 0; x < 16; x++) {
            const ch = row[x];
            if (ch === '.') continue;
            g[y * 16 + x] = ch === '_' ? null : ch;
          }
        }
      }
      const res = new Array(256).fill(null);
      const solid = (xx, yy) => xx >= 0 && xx < 16 && yy >= 0 && yy < 16 && g[yy * 16 + xx] && g[yy * 16 + xx] !== 'k';
      for (let i = 0; i < 256; i++) {
        const ch = g[i];
        if (ch) {
          if (ch === 'k') { res[i] = OUTLINE; continue; }
          const col = pal[ch];
          if (!col) throw new Error('palette key "' + ch + '" missing');
          res[i] = col;
        } else if (part.ol !== false) {
          const x = i & 15, y = i >> 4;
          if (solid(x - 1, y) || solid(x + 1, y) || solid(x, y - 1) || solid(x, y + 1)) res[i] = OUTLINE;
        }
      }
      for (let i = 0; i < 256; i++) if (res[i]) out[i] = res[i];
    }
    return out;
  }

  function newCanvas() {
    if (typeof document !== 'undefined' && document.createElement) return document.createElement('canvas');
    return new OffscreenCanvas(16, 16);
  }
  function toCanvas(pix) {
    const c = newCanvas();
    c.width = 16; c.height = 16;
    const g = c.getContext('2d');
    const img = g.createImageData(16, 16);
    for (let i = 0; i < 256; i++) {
      const col = pix[i];
      if (!col) continue;
      const v = parseInt(col.slice(1), 16);
      img.data[i * 4] = (v >> 16) & 255;
      img.data[i * 4 + 1] = (v >> 8) & 255;
      img.data[i * 4 + 2] = v & 255;
      img.data[i * 4 + 3] = 255;
    }
    g.putImageData(img, 0, 0);
    return c;
  }

  // ---------------------------------------------------------------------------
  // Palette
  // ---------------------------------------------------------------------------
  const P = {
    skin: '#f8c8a0', skinS: '#d8906c', skinL: '#fce4c8',
    white: '#f8f8f8', grey1: '#c0c8d0', grey2: '#8890a0', grey3: '#505868',
    red: '#e84830', redS: '#a82818',
    blue: '#3878f8', blueS: '#1848b0', blueL: '#90c0f8',
    green: '#48b848', greenS: '#207830',
    gold: '#f8d038', goldS: '#c08818',
    purple: '#9050c8', purpleS: '#582888',
    brown: '#b87838', brownS: '#784820', brownD: '#482810',
    orange: '#f89838', pink: '#f890b8',
  };
  const HAIR_C = {
    brown: { H: P.brown, h: P.brownS, I: '#d8a060' },
    dbrown: { H: '#8c5428', h: '#5c3014', I: '#b87838' },
    chestnut: { H: '#b0582c', h: '#703014', I: '#e08850' },
    black: { H: '#403850', h: '#241c30', I: '#6c6484' },
    blond: { H: P.gold, h: P.goldS, I: '#f8f0a8' },
    orange: { H: P.orange, h: '#c05818', I: '#f8c880' },
    red: { H: '#d03828', h: '#881818', I: '#f07058' },
    ginger: { H: '#e86830', h: '#a83c14', I: '#f8a868' },
    white: { H: P.white, h: P.grey1, I: P.white },
    grey: { H: P.grey1, h: P.grey2, I: P.white },
    pink: { H: '#f8a0c8', h: '#d0608c', I: '#fcd8e8' },
  };

  // ---------------------------------------------------------------------------
  // Library of layers.  Each entry: { down, left, up } where each value is a
  // template (same for both frames) or [frame0, frame1].
  // Adult layout: head fill rows 2-8 (outline rows 1 & 9), body fill rows 10-14.
  // Kid layout:   head fill rows 4-9, body fill rows 11-14.
  // ---------------------------------------------------------------------------
  const L = {};

  // ---- faces ---------------------------------------------------------------
  L.face = {
    down: tpl(`
      @2
      ....SSSSSSSS....
      ...SSSSSSSSSS...
      ...SSSSSSSSSS...
      ...SSSSSSSSSS...
      ...SSkSSSSkSS...
      ...SSkSSSSkSs...
      ....sSSSSSSs....
    `),
    left: tpl(`
      @2
      ....SSSSSSSS....
      ...SSSSSSSSSS...
      ...SSSSSSSSSS...
      ...SSSSSSSSSS...
      ...SkSSSSSSSS...
      ...SkSSSSSSSs...
      ....SSSSSSss....
    `),
    up: tpl(`
      @2
      ....SSSSSSSS....
      ...SSSSSSSSSS...
      ...SSSSSSSSSS...
      ...SSSSSSSSSS...
      ...SSSSSSSSSS...
      ...SSSSSSSSSs...
      ....sSSSSSSs....
    `),
  };
  L.face_kid = {
    down: tpl(`
      @4
      .....SSSSSS.....
      ....SSSSSSSS....
      ....SSSSSSSS....
      ....SkSSSSkS....
      ....SkSSSSkS....
      .....sSSSSs.....
    `),
    left: tpl(`
      @4
      .....SSSSSS.....
      ....SSSSSSSS....
      ....SSSSSSSS....
      ....SkSSSSSS....
      ....SkSSSSSs....
      .....SSSSSs.....
    `),
    up: tpl(`
      @4
      .....SSSSSS.....
      ....SSSSSSSS....
      ....SSSSSSSS....
      ....SSSSSSSS....
      ....SSSSSSSs....
      .....sSSSSs.....
    `),
  };

  // ---- hair ----------------------------------------------------------------
  L.hair_short = {
    down: tpl(`
      @2
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ...HHHHHHHHHh...
      ...HHHHHHHHHh...
      ...HH......hh...
      ...H........h...
    `),
    left: tpl(`
      @2
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ...HHHHHHHHHh...
      ...HHHHHHHHHh...
      .......H.HHHh...
      .........HHHh...
      .........hhh....
    `),
    up: tpl(`
      @2
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ...HHHHHHHHHh...
      ...HHHHHHHHHh...
      ...HHHHHHHHHh...
      ...hHHHHHHHhh...
      ....hhhhhhhh....
    `),
  };
  L.hair_swept = {
    down: tpl(`
      @1
      ........HH......
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ...HHHHHHHHHh...
      ...HHHHHHHSSh...
      ...HH.......h...
      ...H........h...
    `),
    left: tpl(`
      @1
      .........HH.....
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ...HHHHHHHHHh...
      ...HHHHHHHHHh...
      .......H.HHHh...
      .........HHHh...
      .........hhh....
    `),
    up: tpl(`
      @1
      ........HH......
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ...HHHHHHHHHh...
      ...HHHHHHHHHh...
      ...HHHHHHHHHh...
      ...hHHHHHHHhh...
      ....hhhhhhhh....
    `),
  };
  L.hair_long = {
    down: tpl(`
      @2
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ..HHHHHHHHHHhh..
      ..HHHHHSHHHHhh..
      ..HH........hh..
      ..HH........hh..
      ..HH........hh..
      ..HH........hh..
      ..H..........h..
      ..h..........h..
    `),
    left: tpl(`
      @2
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ...HHHHHHHHHhh..
      ...HHHHHHHHHhh..
      .......H.HHHhh..
      .........HHHhh..
      ........HHhHhh..
      ........HHhHhh..
      ........hHhHhh..
      .........hhhh...
    `),
    up: tpl(`
      @2
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ..HIIHHIIHHHhh..
      ..HHHHHHHHHHhh..
      ..HHHHHHHHHHhh..
      ..HHHhHHHHhHhh..
      ..HHHhHHHHhHhh..
      ..hHHhHHHHhHhh..
      ...hHhHHHhHhh...
      ....hhhhhhhh....
    `),
  };
  L.hair_wavy = {
    down: tpl(`
      @2
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ..HHHHHHHHHHhh..
      ..HHHHSHHHHHhh..
      .HHH........hhh.
      .HHH........hhh.
      ..HH........hh..
      .HHh........hhh.
      .HHh........Hhh.
      ..h..........h..
    `),
    left: tpl(`
      @2
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ...HHHHHHHHHhh..
      ...HHHHHHHHHhhh.
      .......H.HHHhhh.
      .........HHHhhh.
      ........HHHHhh..
      ........HHHHhhh.
      ........hHHHhhh.
      .........hhhh...
    `),
    up: tpl(`
      @2
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ..HIIHHIIHHHhh..
      .HHHHHHHHHHHhhh.
      .HHHHHHHHHHHhhh.
      ..HHHhHHHHHHhh..
      .HHHHhHHHHHHhhh.
      .HHHHHHHHhHHhhh.
      .hHHHHHHHhHHhhh.
      ..hhhhhhhhhhhh..
    `),
  };
  L.hair_bun = {
    down: tpl(`
      @1
      ......HIIh......
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ...HHHHHHHHHh...
      ...HHSSSSSHHh...
      ...H........h...
      ...H........h...
    `),
    left: tpl(`
      @1
      ..........HIh...
      ....HIIHHHIHHh..
      ...HIHHHHHhHHh..
      ...HHHHHHHHhh...
      ...SHHHHHHHHh...
      .......H.HHHh...
      .........HHHh...
      .........hhh....
    `),
    up: tpl(`
      @1
      ......HIIh......
      ....HIIIHHHH....
      ...HIHHhhHHHh...
      ...HHHHHHHHHh...
      ...HHHHHHHHHh...
      ...HHHHHHHHHh...
      ...hHHHHHHHhh...
      ....hhhhhhhh....
    `),
  };
  L.hair_bald = {
    down: tpl(`
      @2
      ....SLLSSSSS....
      ...SLSSSSSSSs...
      @5
      ...H........H...
      ...HH......HH...
      ...H........H...
    `),
    left: tpl(`
      @2
      ....SLLSSSSS....
      ...SLSSSSSSSs...
      @5
      ..........HH....
      .........HHHh...
      .........HHHh...
      .........hhh....
    `),
    up: tpl(`
      @2
      ....SLLSSSSS....
      ...SLSSSSSSSs...
      @5
      ...HH......Hh...
      ...HHHHHHHHHh...
      ...hHHHHHHHHh...
      ....hhhhhhhh....
    `),
  };
  L.mustache = {
    down: tpl(`
      @8
      ....hHHHHHHh....
      .....SSSSSS.....
    `),
    left: tpl(`
      @8
      ...hHH..........
      ....SSSSs.......
    `),
  };
  L.beard = {
    down: tpl(`
      @8
      ...WWWWWWWWWw...
      ....WWWWWWWw....
      .....WWWWWw.....
      ......WWw.......
    `),
    left: tpl(`
      @8
      ...WWWWW........
      ...WWWWW........
      ....WWWw........
      .....Ww.........
    `),
  };
  L.beard_long = {
    down: tpl(`
      @7
      ...W........W...
      ...WWWWWWWWWw...
      ....WWWWWWWw....
      ....WWWWWWWw....
      .....WWWWWw.....
      .....WWWWWw.....
      ......WWWw......
      .......Ww.......
    `),
    left: tpl(`
      @7
      .......W........
      ...WWWWW........
      ...WWWWW........
      ...WWWWw........
      ....WWWw........
      ....WWw.........
      .....Ww.........
    `),
  };

  // hero: spiky chestnut hair, red headband with trailing tails
  L.hero_hair_m = {
    down: [tpl(`
      @1
      ...H...HH...H...
      ...HH.HHHH.HH...
      ..HHHIHHHHHHHh..
      ..HIHHHHHHHHhh..
      ...EEEEEEEEEEe..
      ...Hh......hhEe.
      ...H........hEe.
      ..............e.
    `), tpl(`
      @1
      ...H...HH...H...
      ...HH.HHHH.HH...
      ..HHHIHHHHHHHh..
      ..HIHHHHHHHHhh..
      ...EEEEEEEEEEeE.
      ...Hh......hhEe.
      ...H........h.e.
    `)],
    left: [tpl(`
      @1
      ......H...H.....
      .....HHH.HHH.H..
      ...HHIHHHHHHHHH.
      ...HIHHHHHHHHHh.
      ...EEEEEEEEEEE..
      .......H.HHHhEE.
      .........HHHhEe.
      .........hhh..e.
    `), tpl(`
      @1
      ......H...H.....
      .....HHH.HHH.H..
      ...HHIHHHHHHHHH.
      ...HIHHHHHHHHHh.
      ...EEEEEEEEEEEE.
      .......H.HHHhEe.
      .........HHHh.e.
      .........hhh....
    `)],
    up: [tpl(`
      @1
      ...H...HH...H...
      ...HH.HHHH.HH...
      ..HHHIHHHHHHHh..
      ..HHHHHHHHHHhh..
      ...EEEEEEEEEEe..
      ...HHHHEEHHHhh..
      ...hHHHEeHHhh...
      ....hhhEehhh....
      .......Ee.......
    `), tpl(`
      @1
      ...H...HH...H...
      ...HH.HHHH.HH...
      ..HHHIHHHHHHHh..
      ..HHHHHHHHHHhh..
      ...EEEEEEEEEEe..
      ...HHHHEEHHHhh..
      ...hHHHHEeHhh...
      ....hhhhEehh....
      ........Ee......
    `)],
  };
  L.hero_hair_f = {
    down: tpl(`
      @2
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ...HHHHHHHHHh...
      ...EEEEEEEEEe...
      ...HH......hhH..
      ...H........hHh.
      ...H.........Hh.
      .............h..
    `),
    left: [tpl(`
      @2
      ....HIIHHHHH....
      ...HIHHHHHHHhh..
      ...HHHHHHHHHhHH.
      ...EEEEEEEEEEhH.
      .......H.HHHhHH.
      .........HHHhHh.
      .........hhh.Hh.
      .............Hh.
      ............hh..
    `), tpl(`
      @2
      ....HIIHHHHH....
      ...HIHHHHHHHhh..
      ...HHHHHHHHHhHH.
      ...EEEEEEEEEEhH.
      .......H.HHHhHH.
      .........HHHhHh.
      .........hhh.Hh.
      ............Hh..
      ...........hh...
    `)],
    up: [tpl(`
      @2
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ...HHHHHHHHHh...
      ...EEEEEEEEEe...
      ...HHHHIHHHHh...
      ...hHHHIHHHhh...
      ....hhhHHhhh....
      ......HIHh......
      ......HHhh......
      .......hh.......
    `), tpl(`
      @2
      ....HIIHHHHH....
      ...HIHHHHHHHh...
      ...HHHHHHHHHh...
      ...EEEEEEEEEe...
      ...HHHHIHHHHh...
      ...hHHHIHHHhh...
      ....hhhHHhhh....
      .......HIHh.....
      .......HHhh.....
      ........hh......
    `)],
  };
  // fighter: white headband over hair
  L.headband = {
    down: tpl(`
      @5
      ...EEEEEEEEEe...
    `),
    left: tpl(`
      @5
      ...EEEEEEEEEEe..
      ............Ee..
      .............e..
    `),
    up: tpl(`
      @5
      ...EEEEEEEEEe...
      .......Ee.......
      .......ee.......
    `),
  };
  L.hair_buns = {
    down: tpl(`
      @1
      .HHH........HHh.
      .HIH.HIHHHH.Hhh.
      .RRHHHHHHHHHHRR.
      ...HHHHHHHHHh...
      ...HHHHHHHHHh...
      ...HH......hh...
      ...H........h...
    `),
    left: tpl(`
      @1
      .........HHh....
      ....HIIHHIHhh...
      ...HIHHHHHRRHh..
      ...HHHHHHHHHh...
      ...HHHHHHHHHh...
      .......H.HHHh...
      .........HHHh...
      .........hhh....
    `),
    up: tpl(`
      @1
      .HHH........HHh.
      .HIH.HIHHHH.Hhh.
      .RRHHHHHHHHHHRR.
      ...HHHHHHHHHh...
      ...HHHHHHHHHh...
      ...HHHHHHHHHh...
      ...hHHHHHHHhh...
      ....hhhhhhhh....
    `),
  };
  L.hair_wild = {
    down: tpl(`
      @2
      ....SLLSSSSS....
      .W.SLSSSSSSSs.W.
      .WWCXXCCCCXXCWW.
      .WWCxxCCCCxxCWw.
      ..WW........Ww..
      .WW..........Ww.
      ..w..........w..
    `),
    left: tpl(`
      @2
      ....SLLSSSSS....
      ...SLSSSSSSSsW..
      ..CXXCCCCCCCWWW.
      ..CxxSSSSSSWWw..
      .........WWWWWw.
      ........WW.WWw..
      .........w..w...
    `),
    up: tpl(`
      @2
      ....SLLSSSSS....
      .W.SLSSSSSSSs.W.
      .WWCCCCCCCCCCWW.
      ..WWWWWWWWWWWw..
      .WWWWWWWWWWWWWw.
      ..wWwWWwWWwWww..
      ...w..w..w..w...
    `),
  };
  L.hair_kid_messy = {
    down: tpl(`
      @3
      .....H.HH.H.....
      ....HIIHHHHH....
      ...HHIHHHHHHh...
      ....HHHHHHHh....
      ....H......h....
    `),
    left: tpl(`
      @3
      ......H.HH.H....
      ....HIIHHHHHH...
      ....HIHHHHHHhH..
      ....HHHHHHHHh...
      .......H.HHh....
      .........HHh....
    `),
    up: tpl(`
      @3
      .....H.HH.H.....
      ....HIIHHHHH....
      ...HHIHHHHHHh...
      ....HHHHHHHh....
      ....HHHHHHHh....
      ....hHHHHHhh....
      .....hhhhhh.....
    `),
  };
  L.hair_kid_pigtails = {
    down: tpl(`
      @4
      .....HIIHHh.....
      ....HIHHHHHh....
      .RR.HHHHHHHh.RR.
      .HH..........Hh.
      .HH..........Hh.
      .hH..........Hh.
      ..h..........h..
    `),
    left: tpl(`
      @4
      .....HIIHHh.....
      ....HIHHHHHhh...
      ....HHHHHHHhRR..
      .......H.HHhHh..
      .........HhhHh..
      ............Hh..
      ............h...
    `),
    up: tpl(`
      @4
      .....HIIHHh.....
      ....HIHHHHHh....
      .RR.HHHHHHHh.RR.
      .HH.HHHHHHHh.Hh.
      .HH.hHHHHHhh.Hh.
      .hH..hhhhhh..Hh.
      ..h..........h..
    `),
  };

  // ---- headwear -------------------------------------------------------------
  L.crown = {
    down: tpl(`
      @1
      ....G..GG..G....
      ....GGGGGGGG....
      ...gGRGGGGRGg...
    `),
    left: tpl(`
      @1
      ....G..G..G.....
      ....GGGGGGGG....
      ...gGGRGGRGGg...
    `),
    up: tpl(`
      @1
      ....G..GG..G....
      ....GGGGGGGG....
      ...gGRGGGGRGg...
    `),
  };
  L.tiara = {
    down: tpl(`
      @1
      .......GG.......
      ......GJJG......
      ....GG....GG....
    `),
    left: tpl(`
      @1
      .....G..........
      ....GJG.........
      .......GG.......
    `),
    up: tpl(`
      @1
      .......GG.......
      ......GGGG......
    `),
  };
  L.tiara_small = {
    down: tpl(`
      @2
      ......GJJG......
      .....G....G.....
    `),
    left: tpl(`
      @2
      ....GJG.........
      .......GG.......
    `),
    up: tpl(`
      @2
      ......GGGG......
    `),
  };
  L.helmet_crest = {
    down: tpl(`
      @1
      ......RRrr......
      ....MWRRrrMm....
      ...MWMMMMMMMm...
      ...MMMMMMMMMm...
      ...mmmmmmmmmm...
      ...M........m...
      ...M........m...
    `),
    left: tpl(`
      @1
      ......RRRRR.....
      ....MWMMMMRRr...
      ...MWMMMMMMMRr..
      ...MMMMMMMMMmr..
      ...mmmmmmmmmm...
      .......MMMMMm...
      .......MMMMm....
      .........mm.....
    `),
    up: tpl(`
      @1
      ......RRrr......
      ....MWRRrrMm....
      ...MWMMRrMMMm...
      ...MMMMRrMMMm...
      ...mmmmmmmmmm...
      ...MMMMMMMMMm...
      ...mMMMMMMMmm...
      ....mmmmmmmm....
    `),
  };
  L.helmet_nose = {
    down: tpl(`
      @2
      ....MWMMMMMm....
      ...MWMMMMMMMm...
      ...MMMMMMMMMm...
      ...mmmmMMmmmm...
      ...n...Mm...n...
      ...n...Mm...n...
    `),
    left: tpl(`
      @2
      ....MWMMMMMm....
      ...MWMMMMMMMm...
      ...MMMMMMMMMm...
      ..mmmmmmmmmmm...
      ..M......nnnn...
      ..M......nnnn...
      .........nnn....
    `),
    up: tpl(`
      @2
      ....MWMMMMMm....
      ...MWMMMMMMMm...
      ...MMMMMMMMMm...
      ...mmmmmmmmmm...
      ...nnnnnnnnnn...
      ...nnnnnnnnnn...
      ....nnnnnnnn....
    `),
  };
  L.helmet_horns = {
    down: tpl(`
      @1
      .O............O.
      .O..MMMNNNNN..O.
      .OOMMNNNNNNNnOO.
      ..OMNNNNNNNNnO..
      ...NNNNNNNNNn...
      ...NkQkkkkQkN...
      ...NNNNnnNNNn...
      ....nNNNNNNn....
    `),
    left: tpl(`
      @1
      ...........OO...
      ....MMMNNNOO....
      ...MMNNNOONNn...
      ...MNNNNNNNNn...
      ...NNNNNNNNNn...
      ..NkQkNNNNNNn...
      ...NNNNNNNNNn...
      ....nNNNNNNn....
    `),
    up: tpl(`
      @1
      .O............O.
      .O..MMMNNNNN..O.
      .OOMMNNNNNNNnOO.
      ..OMNNNNNNNNnO..
      ...NNNNNNNNNn...
      ...NNNNNNNNNn...
      ...nNNNNNNNNn...
      ....nnnnnnnn....
    `),
  };
  L.mitre = {
    down: tpl(`
      @1
      ......EEEe......
      ...__EEGGEe__...
      ...__EGGGGe__...
      ...__EEGGEe__...
      ...FFFFFFFFFf...
      ...H........h...
      ...H........h...
    `),
    left: tpl(`
      @1
      ......EEEe......
      ...__EEEEEe__...
      ...__EFFEEe__...
      ...__EEEEEe__...
      ...FFFFFFFFFf...
      .......H.HHHh...
      .........HHHh...
      .........hhh....
    `),
    up: tpl(`
      @1
      ......EEEe......
      ...__EEFFEe__...
      ...__EEFFEe__...
      ...__EEFFEe__...
      ...FFFFFFFFFf...
      ...HHHHFfHHHh...
      ...hHHHFfHHhh...
      ....hhhFfhhh....
      .......Ff.......
    `),
  };
  L.hood = {
    down: tpl(`
      @2
      ....EEEEEEEE....
      ...EEEEGGEEEe...
      ...EEEEEEEEEe...
      ..EEWWWWWWWWee..
      ..EEW......Wee..
      ..EEW......Wee..
      ..EEEW....Weee..
      ...EEEEEEEEEe...
      ....eeeeeeee....
    `),
    left: tpl(`
      @2
      ....EEEEEEEE....
      ...EEEEEEEEEe...
      ...EEEEEEEEEe...
      ..EEEEEEEEEEee..
      ......WEEEEEee..
      ......WEEEEEee..
      .....WEEEEEeee..
      .....EEEEEEee...
      ......eeeeee....
    `),
    up: tpl(`
      @2
      ....EEEEEEEE....
      ...EEEEEEEEEe...
      ...EEEEEEEEEe...
      ..EEEEEEEEEEee..
      ..EEEEEEEEEEee..
      ..EEEEEEEEEEee..
      ..eEEEEEEEEEee..
      ...eEEEEEEEee...
      ....eeeeeeee....
    `),
  };
  L.hood_pointed = {
    down: tpl(`
      @1
      ........EE......
      ....EEEEEEEe....
      ...EEEEEEEEEe...
      ...EEEEEEEEEe...
      ..EEeeeeeeeeee..
      ..EEe......eee..
      ..EEe......eee..
      ..EEEe....eeee..
      ...EEEEEEEEEe...
      ....eeeeeeee....
    `),
    left: tpl(`
      @1
      ..........EE....
      ....EEEEEEEEe...
      ...EEEEEEEEEe...
      ...EEEEEEEEEe...
      ..EEEEEEEEEEee..
      ......eEEEEEee..
      ......eEEEEEee..
      .....eEEEEEeee..
      .....EEEEEEee...
      ......eeeeee....
    `),
    up: tpl(`
      @1
      ........EE......
      ....EEEEEEEe....
      ...EEEEEEEEEe...
      ...EEEEEEEEEe...
      ..EEEEEEEEEEee..
      ..EEEEEEEEEEee..
      ..EEEEEEEEEEee..
      ..eEEEEEEEEEee..
      ...eEEEEEEEee...
      ....eeeeeeee....
    `),
  };
  L.thief_hood = {
    down: tpl(`
      @2
      ....IIIEEEEE....
      ...IEEEEEEEEe...
      ...EEEEEEEEEe...
      ..EEEEEEEEEEee..
      ..EE........ee..
      ..EE........ee..
      ..EEEFFFFFFeee..
      ...eEEEEEEEe....
    `),
    left: tpl(`
      @2
      ....IIIEEEEE....
      ...IEEEEEEEEe...
      ...EEEEEEEEEe...
      ..EEEEEEEEEEee..
      ......EEEEEEee..
      ......EEEEEEee..
      ...FFFEEEEEeee..
      .....eEEEEEe....
    `),
    up: tpl(`
      @2
      ....IIIEEEEE....
      ...IEEEEEEEEe...
      ...EEEEEEEEEe...
      ..EEEEEEEEEEee..
      ..EEEEEEEEEEee..
      ..EEEEEEEEEEee..
      ..eEEEEEEEEEee..
      ...eEEEEEEEe....
    `),
  };
  L.veil = {
    down: tpl(`
      @2
      ....FFFEEEEE....
      ...FEEEEEEEEe...
      ..EFWWWWWWWWee..
      ..EEW......Wee..
      ..EEW......Wee..
      ..EEW......Wee..
      ..EEEWWWWWWeee..
      ..EEEEWWWWeeee..
      ..EE........ee..
      ..Ee........ee..
    `),
    left: tpl(`
      @2
      ....FFFEEEEE....
      ...FEEEEEEEEe...
      ..EWWWWWEEEEee..
      ........WEEEee..
      ........WEEEee..
      ........WEEEee..
      ...WWWWWWEEEee..
      ....WWWWEEEEee..
      .......EEEEEee..
      ........EEEEee..
      ........eeeeee..
    `),
    up: tpl(`
      @2
      ....FFFEEEEE....
      ...FEEEEEEEEe...
      ..FEEEEEEEEEee..
      ..FEEEEEEEEEee..
      ..EEEEEEEEEEee..
      ..EEEEEEEEEEee..
      ..EEEEEEEEEEee..
      ..EEEEEEEEEEee..
      ..eEEEEEEEEEee..
      ...eEEEEEEEee...
      ....WWWWWWWW....
    `),
  };
  L.witch_hat = {
    down: tpl(`
      @1
      .........EE.....
      ....___EEEe_....
      ...___FFFFFf_...
      .EEEEEEEEEEEEEe.
      ...hhhhhhhhhh...
    `),
    left: tpl(`
      @1
      ..........EE....
      ....___EEEe_....
      ...___FFFFFf_...
      .EEEEEEEEEEEEEe.
      ...hhhhhhhhhh...
    `),
    up: tpl(`
      @1
      .........EE.....
      ....___EEEe_....
      ...___FFFFFf_...
      .EEEEEEEEEEEEEe.
      ...hhhhhhhhhh...
    `),
  };
  L.turban = {
    down: tpl(`
      @1
      .....EEEEEe.....
      ...EFFEEEEEEe...
      ..EFEEEEEEEEee..
      ..eeeeeGGeeeee..
      ..EEEEEEEEEEee..
      ...H........h...
      ...H........h...
    `),
    left: tpl(`
      @1
      ....EEEEEEe.....
      ...EFFEEEEEEe...
      ..EFEEEEEEEEee..
      ..Geeeeeeeeeee..
      ..EEEEEEEEEEee..
      .......H.HHHh...
      .........HHHh...
      .........hhh....
    `),
    up: tpl(`
      @1
      .....EEEEEe.....
      ...EFFEEEEEEe...
      ..EFEEEEEEEEee..
      ..eeeeeeeeeeee..
      ..EEEEEEEEEEee..
      ...HHHHHHHHHh...
      ...hHHHHHHHhh...
      ....hhhhhhhh....
    `),
  };
  L.bandana = {
    down: tpl(`
      @2
      ....EEEEEEEE....
      ...EEEEEEEEEe...
      ...eEEEEEEEee...
      ...HHHHHHHHHh...
      ...HH......hh...
      ...H........h...
    `),
    left: tpl(`
      @2
      ....EEEEEEEE....
      ...EEEEEEEEEe...
      ...eEEEEEEEEee..
      ...HHHHHHHHHhEe.
      .......H.HHHhEe.
      .........HHHh.e.
      .........hhh....
    `),
    up: tpl(`
      @2
      ....EEEEEEEE....
      ...EEEEEEEEEe...
      ...eEEEEEEEee...
      ...HHHHEEHHHh...
      ...HHHHEeHHHh...
      ...hHHHEeHHhh...
      ....hhhhehhh....
    `),
  };
  L.jester_hat = {
    down: tpl(`
      @2
      ....EEEEFFFF....
      ..EEEEEEFFFFFF..
      .EEEEEEEFFFFFFF.
      .EE.eeeeffff.FF.
      .G............G.
    `),
    left: tpl(`
      @2
      ....EEEEFFFF....
      ..EEEEEEFFFFFF..
      .EEEEEEEFFFFFFF.
      .EE.eeeeffff.FF.
      .G.....f.fff..G.
      .........ff.....
    `),
    up: tpl(`
      @2
      ....FFFFEEEE....
      ..FFFFFFEEEEEE..
      .FFFFFFFEEEEEEE.
      .FF.ffffeeee.EE.
      .G..ffffeeee..G.
      ....ffffeeee....
      .....ffffee.....
    `),
  };
  L.bunny_ears = {
    down: tpl(`
      @1
      ...EE......EE...
      ...EF_...._FE...
      ...EF_...._FE...
      ...GGGGGGGGGG...
    `),
    left: tpl(`
      @1
      .......EE.......
      ......_EF_......
      ......_EF_......
      ...GGGGGGGGG....
    `),
    up: tpl(`
      @1
      ...EE......EE...
      ...EE_...._EE...
      ...EE_...._EE...
      ...GGGGGGGGGG...
    `),
  };
  L.nightcap = {
    down: tpl(`
      @1
      .....EEEEEE.....
      ....EEGEEEEEe...
      ...EEEEEEEGEEEe.
      ...eeeeeeeeeeeE.
      ...H........hEe.
      ...H........h.W.
      ..............W.
    `),
    left: tpl(`
      @1
      ....EEEEEE......
      ...EEGEEEEEe....
      ...EEEEEEGEEEe..
      ...eeeeeeeeeeEe.
      .......H.HHHhEe.
      .........HHHh.W.
      .........hhh..W.
    `),
    up: tpl(`
      @1
      .....EEEEEE.....
      ....EEGEEEEEe...
      ...EEEEEEEGEEEe.
      ...eeeeeeeeeeeE.
      ...HHHHHHHHHhEe.
      ...HHHHHHHHHh.W.
      ...hHHHHHHHhh.W.
      ....hhhhhhhh....
    `),
  };
  L.feather_cap = {
    down: tpl(`
      @1
      ............FF..
      ....EEEEEEE.Ff..
      ...EEEEEEEEFf...
      ...eeeeeeeeeF...
      ...HHHHHHHHHh...
      ...HH......hh...
      ...H........h...
    `),
    left: tpl(`
      @1
      ...........FF...
      ....EEEEEE.Ff...
      ...EEEEEEEEFf...
      ..EEeeeeeeeeF...
      ...HHHHHHHHHh...
      .......H.HHHh...
      .........HHHh...
      .........hhh....
    `),
    up: tpl(`
      @1
      ..FF............
      ..fF.EEEEEEE....
      ...fFEEEEEEEE...
      ...FeeeeeeeeE...
      ...HHHHHHHHHh...
      ...HHHHHHHHHh...
      ...hHHHHHHHhh...
      ....hhhhhhhh....
    `),
  };

  // ---- bodies --------------------------------------------------------------
  L.tunic = {
    down: [tpl(`
      @10
      ....aYYAAAAa....
      ....aYAAAAaa....
      ....SCCCCCCS....
      .....BB..dd.....
      .....DD.........
    `), tpl(`
      @10
      ....aYYAAAAa....
      ....aYAAAAaa....
      ....SCCCCCCS....
      .....dd..BB.....
      .........DD.....
    `)],
    left: [tpl(`
      @10
      .....YYAAAA.....
      .....YAaAAa.....
      .....CCSCCC.....
      ......BBB.......
      .....DDDd.......
    `), tpl(`
      @10
      .....YYAAAA.....
      ....SaAAAAa.....
      .....CCCCCC.....
      .....BB..BB.....
      ....DD...dD.....
    `)],
    up: [tpl(`
      @10
      ....aYYAAAAa....
      ....aYAAAAaa....
      ....SCCCCCCS....
      .....BB..dd.....
      .....DD.........
    `), tpl(`
      @10
      ....aYYAAAAa....
      ....aYAAAAaa....
      ....SCCCCCCS....
      .....dd..BB.....
      .........DD.....
    `)],
  };
  L.skirt = {
    down: [tpl(`
      @10
      ....aYYAAAAa....
      ....aYAAAAaa....
      ....SCCCCCCS....
      ...aAYAAAAAAa...
      .....DD.........
    `), tpl(`
      @10
      ....aYYAAAAa....
      ....aYAAAAaa....
      ....SCCCCCCS....
      ...aAYAAAAAAa...
      .........DD.....
    `)],
    left: [tpl(`
      @10
      .....YYAAAA.....
      .....YAaAAa.....
      .....CCSCCC.....
      ....AYAAAAAa....
      ......DDd.......
    `), tpl(`
      @10
      .....YYAAAA.....
      ....SaAAAAa.....
      .....CCCCCC.....
      ....AYAAAAAa....
      ....DD...dD.....
    `)],
    up: [tpl(`
      @10
      ....aYYAAAAa....
      ....aYAAAAaa....
      ....SCCCCCCS....
      ...aAYAAAAAAa...
      .....DD.........
    `), tpl(`
      @10
      ....aYYAAAAa....
      ....aYAAAAaa....
      ....SCCCCCCS....
      ...aAYAAAAAAa...
      .........DD.....
    `)],
  };
  L.robe = {
    down: [tpl(`
      @10
      ....aYYAAAAa....
      ....aYAAAAaa....
      ....SYAAAAaS....
      ...aAYAAAAAAa...
      .....DD.........
    `), tpl(`
      @10
      ....aYYAAAAa....
      ....aYAAAAaa....
      ....SYAAAAaS....
      ...aAYAAAAAAa...
      .........DD.....
    `)],
    left: [tpl(`
      @10
      .....YYAAAA.....
      .....YAaAAa.....
      .....YASAAa.....
      ....YAAAAAAa....
      .....DDD........
    `), tpl(`
      @10
      .....YYAAAA.....
      .....YaAAAa.....
      .....YSAAAa.....
      ....YAAAAAAAa...
      ...DD.....dD....
    `)],
    up: [tpl(`
      @10
      ....aYYAAAAa....
      ....aYAAAAaa....
      ....SYAAAAaS....
      ...aAYAAAAAAa...
      .....DD.........
    `), tpl(`
      @10
      ....aYYAAAAa....
      ....aYAAAAaa....
      ....SYAAAAaS....
      ...aAYAAAAAAa...
      .........DD.....
    `)],
  };
  L.dress = {
    down: [tpl(`
      @10
      ....aYYAAAAa....
      ....SYAAAAaS....
      .....aAAAAa.....
      ...aAYAAAAAAa...
      .....DD.........
    `), tpl(`
      @10
      ....aYYAAAAa....
      ....SYAAAAaS....
      .....aAAAAa.....
      ...aAYAAAAAAa...
      .........DD.....
    `)],
    left: [tpl(`
      @10
      .....YYAAAA.....
      .....YaAAAa.....
      .....aSAAAa.....
      ...aYAAAAAAa....
      .....DD.........
    `), tpl(`
      @10
      .....YYAAAA.....
      .....YAaAAa.....
      .....aASAAa.....
      ....aYAAAAAAa...
      ....DD....Dd....
    `)],
    up: [tpl(`
      @10
      ....aYYAAAAa....
      ....SYAAAAaS....
      .....aAAAAa.....
      ...aAYAAAAAAa...
      .....DD.........
    `), tpl(`
      @10
      ....aYYAAAAa....
      ....SYAAAAaS....
      .....aAAAAa.....
      ...aAYAAAAAAa...
      .........DD.....
    `)],
  };
  L.gown = {
    down: [tpl(`
      @10
      ....aAAAAAAa....
      ....SAAAAAAS....
      .....aAAAAa.....
      ....aAYAAAAa....
      ...aAYAAAAAAa...
    `), tpl(`
      @10
      ....aAAAAAAa....
      ....SAAAAAAS....
      .....aAAAAa.....
      ....aAAAAYAa....
      ...aAAAAAAYAa...
    `)],
    left: [tpl(`
      @10
      .....AAAAAA.....
      .....AaAAAA.....
      .....aSAAAa.....
      ....aAYAAAAa....
      ...aAYAAAAAAa...
    `), tpl(`
      @10
      .....AAAAAA.....
      .....AAaAAA.....
      .....aASAAa.....
      ....aAAAYAAa....
      ....aAAAAYAAa...
    `)],
    up: [tpl(`
      @10
      ....aAAAAAAa....
      ....SAAAAAAS....
      .....aAAAAa.....
      ....aAYAAAAa....
      ...aAYAAAAAAa...
    `), tpl(`
      @10
      ....aAAAAAAa....
      ....SAAAAAAS....
      .....aAAAAa.....
      ....aAAAAYAa....
      ...aAAAAAAYAa...
    `)],
  };
  L.armor = {
    down: [tpl(`
      @10
      ...WMMWWMMMMm...
      ...mBMWMMMMBm...
      ....SCCGCCCS....
      .....BB..nn.....
      .....nn.........
    `), tpl(`
      @10
      ...WMMWWMMMMm...
      ...mBMWMMMMBm...
      ....SCCGCCCS....
      .....nn..BB.....
      .........nn.....
    `)],
    left: [tpl(`
      @10
      ....WMMMMMm.....
      .....MMBMMm.....
      .....CCSCCC.....
      ......BBB.......
      .....nnnn.......
    `), tpl(`
      @10
      ....WMMMMMm.....
      ....SBMMMMm.....
      .....CCCCCC.....
      .....BB..BB.....
      ....nn...nn.....
    `)],
    up: [tpl(`
      @10
      ...WMMMMMMMMm...
      ...mBMMMMMMBm...
      ....SCCCCCCS....
      .....BB..nn.....
      .....nn.........
    `), tpl(`
      @10
      ...WMMMMMMMMm...
      ...mBMMMMMMBm...
      ....SCCCCCCS....
      .....nn..BB.....
      .........nn.....
    `)],
  };
  L.armor_f = {
    down: [tpl(`
      @10
      ...WMMWWMMMMm...
      ...mBMWMMMMBm...
      ....SCCGCCCS....
      ...bBBBBBBBBb...
      .....nn.........
    `), tpl(`
      @10
      ...WMMWWMMMMm...
      ...mBMWMMMMBm...
      ....SCCGCCCS....
      ...bBBBBBBBBb...
      .........nn.....
    `)],
    left: [tpl(`
      @10
      ....WMMMMMm.....
      .....MMBMMm.....
      .....CCSCCC.....
      ....BBBBBBBb....
      ......nnn.......
    `), tpl(`
      @10
      ....WMMMMMm.....
      ....SBMMMMm.....
      .....CCCCCC.....
      ....BBBBBBBb....
      ....nn...nn.....
    `)],
    up: [tpl(`
      @10
      ...WMMMMMMMMm...
      ...mBMMMMMMBm...
      ....SCCCCCCS....
      ...bBBBBBBBBb...
      .....nn.........
    `), tpl(`
      @10
      ...WMMMMMMMMm...
      ...mBMMMMMMBm...
      ....SCCCCCCS....
      ...bBBBBBBBBb...
      .........nn.....
    `)],
  };
  L.plump = {
    down: [tpl(`
      @10
      ....aYYAAAAa....
      ...aYYAAAAAaa...
      ...SYAAAAAAaS...
      ....BBB..bbb....
      ....DDD.........
    `), tpl(`
      @10
      ....aYYAAAAa....
      ...aYYAAAAAaa...
      ...SYAAAAAAaS...
      ....bbb..BBB....
      .........DDD....
    `)],
    left: [tpl(`
      @10
      .....YYAAAA.....
      ....YYAaAAAa....
      ....YAASAAAa....
      .....BBBBBB.....
      .....DDDDd......
    `), tpl(`
      @10
      .....YYAAAA.....
      ....YAaAAAAa....
      ....ASAAAAAa....
      .....BB..BB.....
      ....DD...dD.....
    `)],
    up: [tpl(`
      @10
      ....aYYAAAAa....
      ...aYYAAAAAaa...
      ...SYAAAAAAaS...
      ....BBB..bbb....
      ....DDD.........
    `), tpl(`
      @10
      ....aYYAAAAa....
      ...aYYAAAAAaa...
      ...SYAAAAAAaS...
      ....bbb..BBB....
      .........DDD....
    `)],
  };
  L.burly = {
    down: [tpl(`
      @10
      ...aYYAAAAAAa...
      ...aYAAAAAAaa...
      ...SCCCCCCCCS...
      ....BBB..bbb....
      ....DDD.........
    `), tpl(`
      @10
      ...aYYAAAAAAa...
      ...aYAAAAAAaa...
      ...SCCCCCCCCS...
      ....bbb..BBB....
      .........DDD....
    `)],
    left: [tpl(`
      @10
      ....YYAAAAAA....
      ....YAAaAAAa....
      ....CCCSCCCC....
      .....BBBBBB.....
      .....DDDDd......
    `), tpl(`
      @10
      ....YYAAAAAA....
      ...SAaAAAAAa....
      ....CCCCCCCC....
      .....BB..BB.....
      ....DD...dD.....
    `)],
    up: [tpl(`
      @10
      ...aYYAAAAAAa...
      ...aYAAAAAAaa...
      ...SCCCCCCCCS...
      ....BBB..bbb....
      ....DDD.........
    `), tpl(`
      @10
      ...aYYAAAAAAa...
      ...aYAAAAAAaa...
      ...SCCCCCCCCS...
      ....bbb..BBB....
      .........DDD....
    `)],
  };
  L.kid_overalls = {
    down: [tpl(`
      @11
      .....ABBBBA.....
      .....SBBBBS.....
      .....BB..DD.....
      .....DD.........
    `), tpl(`
      @11
      .....ABBBBA.....
      .....SBBBBS.....
      .....DD..BB.....
      .........DD.....
    `)],
    left: [tpl(`
      @11
      ......AAAA......
      ......BSBB......
      ......BBB.......
      .....DDD........
    `), tpl(`
      @11
      ......AAAA......
      .....SBBBB......
      .....BB.BB......
      ....DD..DD......
    `)],
    up: [tpl(`
      @11
      .....ABBBBA.....
      .....SBBBBS.....
      .....BB..DD.....
      .....DD.........
    `), tpl(`
      @11
      .....ABBBBA.....
      .....SBBBBS.....
      .....DD..BB.....
      .........DD.....
    `)],
  };
  L.kid_dress = {
    down: [tpl(`
      @11
      .....aAAAAa.....
      .....SAAAAS.....
      ....aAAAAAAa....
      .....DD.........
    `), tpl(`
      @11
      .....aAAAAa.....
      .....SAAAAS.....
      ....aAAAAAAa....
      .........DD.....
    `)],
    left: [tpl(`
      @11
      ......AAAA......
      ......ASAA......
      ....aAAAAAa.....
      .....DDD........
    `), tpl(`
      @11
      ......AAAA......
      .....SAAAA......
      .....aAAAAAa....
      ....DD...DD.....
    `)],
    up: [tpl(`
      @11
      .....aAAAAa.....
      .....SAAAAS.....
      ....aAAAAAAa....
      .....DD.........
    `), tpl(`
      @11
      .....aAAAAa.....
      .....SAAAAS.....
      ....aAAAAAAa....
      .........DD.....
    `)],
  };

  // ---- clothing overlays (drawn in the body part) ---------------------------
  L.gi = {
    down: tpl(`
      @10
      ......aSSa......
      .......aa.......
    `),
    left: tpl(`
      @10
      .....SSa........
    `),
  };
  L.vest = {
    down: tpl(`
      @10
      ....VV....VV....
      ....VV....VV....
    `),
    left: tpl(`
      @10
      .......VVVV.....
      .......VVVv.....
    `),
    up: tpl(`
      @10
      ....VVVVVVVV....
      ....VVVVVVVV....
    `),
  };
  L.apron = {
    down: tpl(`
      @10
      ......V..V......
      .....VVVVVV.....
      .....VVVVVV.....
      .....vVVVVv.....
    `),
    left: tpl(`
      @11
      ....VV..........
      ....VV..........
      ...Vv...........
    `),
    up: tpl(`
      @12
      ......VVVV......
    `),
  };
  L.overalls = {
    down: tpl(`
      @10
      .....V....V.....
      .....VVVVVV.....
      .....VVVVVV.....
    `),
    left: tpl(`
      @10
      ......V.........
      .....VVVV.......
      .....VVVVVV.....
    `),
    up: tpl(`
      @10
      .....V....V.....
      ......V..V......
      .....VVVVVV.....
    `),
  };
  L.tabard = {
    down: tpl(`
      @10
      .....VVVVVV.....
      .....VVGGVV.....
      .....VVVVVV.....
      ......vVVv......
    `),
    left: tpl(`
      @10
      .....VVV........
      .....VVV........
      .....VVv........
      .....vv.........
    `),
    up: tpl(`
      @10
      .....VVVVVV.....
      .....VVVVVV.....
      .....VVVVVV.....
      ......vVVv......
    `),
  };
  L.stole = {
    down: tpl(`
      @10
      ......V..V......
      ......V..V......
      ......V..V......
      ......V..V......
    `),
    left: tpl(`
      @10
      ......V.........
      ......V.........
      .....V..........
    `),
  };
  L.fur_collar = {
    down: tpl(`
      @10
      ...WWkWWWWkWW...
      .......WW.......
      .......WW.......
      ...WWWWWWWWWW...
    `),
    left: tpl(`
      @10
      ....WWWkWWW.....
      .....W..........
      .....W..........
      ....WWWWWWWW....
    `),
    up: tpl(`
      @10
      ...WWkWWWWkWW...
      @13
      ...WWWWWWWWWW...
    `),
  };
  L.robe_trim = {
    down: tpl(`
      @10
      .......GG.......
      .......GG.......
      ....CCCCCCCC....
      ...G...GG...G...
    `),
    left: tpl(`
      @10
      .....G..........
      .....G..........
      .....CCCCCC.....
      ....G...........
    `),
    up: tpl(`
      @12
      ....CCCCCCCC....
    `),
  };
  L.shawl = {
    down: tpl(`
      @11
      ...VVVVVVVVVV...
      ...vVVVVVVVVv...
      ......vVVv......
    `),
    left: tpl(`
      @11
      ....VVVVVVVv....
      ....vVVVVVVv....
      ....vv..........
    `),
    up: tpl(`
      @11
      ...VVVVVVVVVV...
      ...VVVVVVVVVV...
      ....vVVVVVVv....
    `),
  };
  // harlequin diamonds (R / X / G = the kind's two suit colours + gold)
  L.motley = {
    down: [tpl(`
      @11
      ....XRGRXGRX....
      ....SGRXGRXS....
      @13
      .....XX..RR.....
    `), tpl(`
      @11
      ....XRGRXGRX....
      ....SGRXGRXS....
      @13
      .....RR..XX.....
    `)],
    left: [tpl(`
      @11
      .....RGRXGR.....
      .....GRSGRX.....
      @13
      ......XRR.......
    `), tpl(`
      @11
      ....SRGRXGR.....
      .....GRXGRX.....
      @13
      .....XX..RR.....
    `)],
    up: [tpl(`
      @11
      ....XRGRXGRX....
      ....SGRXGRXS....
      @13
      .....XX..RR.....
    `), tpl(`
      @11
      ....XRGRXGRX....
      ....SGRXGRXS....
      @13
      .....RR..XX.....
    `)],
  };
  L.motley_skirt = {
    down: tpl(`
      @11
      ....XRGRXGRX....
      ....SGRXGRXS....
      ...RXGRXGRXGR...
    `),
    left: [tpl(`
      @11
      .....RGRXGR.....
      .....GRSGRX.....
      ....XGRXGRXG....
    `), tpl(`
      @11
      ....SRGRXGR.....
      .....GRXGRX.....
      ....XGRXGRXG....
    `)],
    up: tpl(`
      @11
      ....XRGRXGRX....
      ....SGRXGRXS....
      ...RXGRXGRXGR...
    `),
  };
  L.ruff = {
    down: tpl(`
      @10
      ....GGGGGGGG....
    `),
    left: tpl(`
      @10
      ....GGGGGGG.....
    `),
    up: tpl(`
      @10
      ....GGGGGGGG....
    `),
  };
  L.stripes = {
    down: tpl(`
      @11
      ....FFFFFFFF....
      ....SAAAAAAS....
    `),
    left: [tpl(`
      @11
      .....FFaFFF.....
      .....AASAAA.....
    `), tpl(`
      @11
      ....SFFFFFF.....
      .....AAAAAA.....
    `)],
    up: tpl(`
      @11
      ....FFFFFFFF....
      ....SAAAAAAS....
    `),
  };
  L.soot = {
    down: tpl(`
      @11
      ......x.........
      .........x......
      ......x.........
    `),
    left: tpl(`
      @11
      .......x........
      .....x..........
    `),
    up: tpl(`
      @11
      ........x.......
      ......x.........
    `),
  };

  // ---- behind-the-body layers -------------------------------------------------
  L.cape_back = {
    down: tpl(`
      @10
      ...RRRRRRRRRR...
      ...RRRRRRRRRR...
      ..RRRRRRRRRRRR..
      ..RRRRRRRRRRRR..
      ..rRRRRRRRRRRr..
    `),
    left: [tpl(`
      @10
      ........RRRR....
      ........RRRRr...
      ........RRRRr...
      .........RRRRr..
      .........rRRRr..
    `), tpl(`
      @10
      ........RRRR....
      ........RRRRr...
      ........RRRRRr..
      .........RRRRr..
      ..........rRRr..
    `)],
  };
  L.cape_over = {
    up: [tpl(`
      @10
      ...RRRRRRRRRr...
      ...RRRRRRRRRr...
      ..RRRRRRRRRRrr..
      ..RRRRRRRRRRrr..
      ..rRRRrRRRRrrr..
    `), tpl(`
      @10
      ...RRRRRRRRRr...
      ...RRRRRRRRRr...
      ..RRRRRRRRRRrr..
      ..RRRRRRRRRRrr..
      ..rRRRRRrRRrrr..
    `)],
  };
  L.pack_back = {
    left: tpl(`
      @7
      ..........OOOO..
      .........PPPPPp.
      .........PPPPPp.
      .........PPCPPp.
      .........PPPPPp.
      .........pppppp.
    `),
  };
  L.pack_over = {
    up: tpl(`
      @7
      ...OOOOOOOOOo...
      ...ooooooooooo..
      ...PPPPPPPPPPp..
      ...PPPPPPPPPPp..
      ...PPPCCCCPPPp..
      ...PPPPPPPPPPp..
      ...pppppppppppp.
    `),
  };
  L.pack_straps = {
    down: tpl(`
      @10
      .....C....C.....
      .....C....C.....
    `),
  };
  L.lute_back = {
    down: tpl(`
      @6
      .............T..
      ............Tt..
      ...........Tt...
    `),
    left: tpl(`
      @6
      ...........T....
      ..........Tt....
      .........Tt.....
      ........TTTT....
      ........TTTTt...
      ........TtkTt...
      .........TTt....
    `),
  };
  L.lute_over = {
    up: tpl(`
      @6
      ..T.............
      ..tT............
      ...tT...........
      ....tTTT........
      ....TTTTT.......
      ....TTkTTt......
      ....TTTTTt......
      .....tttt.......
    `),
  };

  // ---- held items (front parts) ---------------------------------------------
  L.hilt = {
    down: tpl(`
      @11
      .............T..
      ............GGG.
      .............m..
      .............m..
    `),
    left: tpl(`
      @11
      ....G...........
      ...TG...........
      ....G.......m...
    `),
    up: tpl(`
      @11
      ..T.............
      .GGG............
      ..m.............
      ..m.............
    `),
  };
  L.spikes = {
    down: tpl(`
      @8
      ..O..........O..
      ..O..........O..
    `),
    left: tpl(`
      @8
      .........O......
      .........O......
    `),
    up: tpl(`
      @8
      ..O..........O..
      ..O..........O..
    `),
  };


  L.staff_b = {
    down: tpl(`
      @6
      .X..............
      .x..............
      .T..............
      .T..............
      .T..............
      .T..............
      .T..............
      .T..............
      .t..............
    `),
    up: tpl(`
      @6
      ..............X.
      ..............x.
      ..............T.
      ..............T.
      ..............T.
      ..............T.
      ..............T.
      ..............T.
      ..............t.
    `),
  };

  L.staff_f = {
    left: tpl(`
      @6
      .X..............
      .x..............
      .T..............
      .T..............
      .T..............
      .SSA............
      .T..............
      .T..............
      .t..............
    `),
  };

  L.grip = {
    down: tpl(`
      @12
      ..SS............
    `),
    up: tpl(`
      @12
      ............SS..
    `),
  };

  L.sage_staff_b = {
    down: tpl(`
      @1
      ..T.............
      .TT.............
      .Tt.............
      .T..............
      .T..............
      .T..............
      ..T.............
      ..T.............
      .T..............
      .T..............
      .T..............
      .T..............
      .T..............
      .t..............
    `),
    up: tpl(`
      @1
      .............T..
      .............TT.
      .............tT.
      ..............T.
      ..............T.
      ..............T.
      .............T..
      .............T..
      ..............T.
      ..............T.
      ..............T.
      ..............T.
      ..............T.
      ..............t.
    `),
  };

  L.sage_staff_f = {
    left: tpl(`
      @1
      ..T.............
      .TT.............
      .Tt.............
      .T..............
      .T..............
      .T..............
      .T..............
      .T..............
      .T..............
      .SSA............
      .T..............
      .T..............
      .T..............
      .t..............
    `),
  };

  L.spear_b = {
    down: tpl(`
      @1
      ..W.............
      .MM.............
      .m..............
      .R..............
      .T..............
      .T..............
      .T..............
      .T..............
      .T..............
      .T..............
      .T..............
      .T..............
      .T..............
      .t..............
    `),
    up: tpl(`
      @1
      .............W..
      .............MM.
      ..............m.
      ..............R.
      ..............T.
      ..............T.
      ..............T.
      ..............T.
      ..............T.
      ..............T.
      ..............T.
      ..............T.
      ..............T.
      ..............t.
    `),
  };

  L.spear_f = {
    left: tpl(`
      @1
      ..W.............
      .MM.............
      .m..............
      .R..............
      .T..............
      .T..............
      .T..............
      .T..............
      .T..............
      .T..............
      .SSB............
      .T..............
      .T..............
      .t..............
    `),
  };

  L.cane_b = {
    down: tpl(`
      @11
      .TT.............
      ..T.............
      ..T.............
      ..t.............
    `),
    up: tpl(`
      @11
      .............TT.
      .............T..
      .............T..
      .............t..
    `),
  };

  L.cane_f = {
    left: tpl(`
      @10
      ..TT............
      ..TS............
      ..T.............
      ..T.............
      ..t.............
    `),
  };

  L.grip_armor = {
    down: tpl(`
      @12
      ..SS............
      ...k............
    `),
    up: tpl(`
      @12
      ............SS..
      ............k...
    `),
  };
  L.grip1 = {
    down: tpl(`
      @12
      ...S............
    `),
    up: tpl(`
      @12
      ............S...
    `),
  };

  L.mustache_small = {
    down: tpl(`
      @8
      .....hHHHHh.....
      ......SSSS......
    `),
    left: tpl(`
      @8
      ...hHH..........
      ....SSSs........
    `),
  };

  L.necklace = {
    down: tpl(`
      @10
      ......GJG.......
    `),
    left: tpl(`
      @10
      .....G..........
    `),
  };



  // ---- whole-sprite specials -------------------------------------------------
  const ghostDown = tpl(`
      @1
      .....WWWWWw.....
      ....WWWWWWWw....
      ...WWWWWWWWWw...
      ...WWkWWWWkWw...
      ...WWkWWWWkWw...
      ...WWWWkkWWWw...
      ..WWWWWWWWWWww..
      ..wWWWWWWWWWww..
      ...WWWWWWWWWw...
      ...WWWWWWWWww...
      ....WWWWWWww....
      .....wWWww......
      .......www......
  `);
  const ghostLeft = tpl(`
      @1
      .....WWWWWw.....
      ....WWWWWWWw....
      ...WWWWWWWWWw...
      ...WkWWWWWWWw...
      ...WkWWWWWWWw...
      ...WWWWWWWWWw...
      ..WWWWWWWWWWw...
      ...WWWWWWWWWww..
      ...WWWWWWWWWWw..
      ....WWWWWWWWWw..
      .....wWWWWWWww..
      .........wWWww..
      ...........www..
  `);
  const ghostUp = tpl(`
      @1
      .....WWWWWw.....
      ....WWWWWWWw....
      ...WWWWWWWWWw...
      ...WWWWWWWWWw...
      ...WWWWWWWWWw...
      ...WWWWWWWWWw...
      ..WWWWWWWWWWww..
      ..wWWWWWWWWWww..
      ...WWWWWWWWWw...
      ...WWWWWWWWww...
      ....WWWWWWww....
      ......wwWWw.....
      ......www.......
  `);
  L.ghost = {
    down: [ghostDown, shift(mirror(ghostDown), 0, 1)],
    left: [ghostLeft, shift(ghostLeft, 0, 1)],
    up: [ghostUp, shift(mirror(ghostUp), 0, 1)],
  };

  L.dog = {
    down: [tpl(`
      @4
      .....AAAAAA.....
      ...EAAAAAAAAE...
      ..EEAAAAAAAAEE..
      ..EEAkAAAAkAEE..
      ..EEAAWWWWAAEE..
      ..EE.AWkkWA.EE..
      ...E..WWWW..E...
      .....aAAAAa.....
      .....AWWWWA.....
      .....AA..AA.....
      .....WW..WW.....
    `), tpl(`
      @4
      .....AAAAAA.....
      ...EAAAAAAAAE...
      ..EEAAAAAAAAEE..
      ..EEAkAAAAkAEE..
      ..EEAAWWWWAAEE..
      ..EE.AWkkWA.EE..
      ...E..WWWW..E...
      .....aAAAAa.....
      .....AWWWWA.....
      .....AA..WW.....
      .....WW.........
    `)],
    left: [tpl(`
      @6
      ....EE..........
      ...AAEE......A..
      ..AkAAE......Aa.
      .kAAAAAAAAAAAA..
      ..WWAAAAAAAAAa..
      ...AAAAAAAAAAa..
      ...AA.A...A.Aa..
      ...AA.A...A.Aa..
      ...WW.W...W.WW..
    `), tpl(`
      @6
      ....EE..........
      ...AAEE.......A.
      ..AkAAE......Aa.
      .kAAAAAAAAAAAA..
      ..WWAAAAAAAAAa..
      ...AAAAAAAAAAa..
      ....AA.A..A.A...
      ...AA..A..A..A..
      ...W...W..W..W..
    `)],
    up: [tpl(`
      @4
      .....AAAAAA.....
      ...EAAAAAAAAE...
      ..EEAAAAAAAAEE..
      ..EEAAAAAAAAEE..
      ..EE.AAAAAA.EE..
      ...E.AAAAAA.E...
      ....AAAAAAAA....
      ....AAAAAAAA....
      ....aAAAAAAa....
      .....AA..AA.....
      .....WW..WW.....
    `), tpl(`
      @4
      .....AAAAAA.....
      ...EAAAAAAAAE...
      ..EEAAAAAAAAEE..
      ..EEAAAAAAAAEE..
      ..EE.AAAAAA.EE..
      ...E.AAAAAA.E...
      ....AAAAAAAA....
      ....AAAAAAAA....
      ....aAAAAAAa....
      .....AA..WW.....
      .....WW.........
    `)],
  };
  L.dog_tail = {
    up: [tpl(`
      @10
      .............A..
      ............A...
      ...........A....
    `), tpl(`
      @10
      ..A.............
      ...A............
      ....A...........
    `)],
  };

  L.cat = {
    down: [tpl(`
      @5
      ....A......A....
      ....AA....AA....
      ....APAAAAPA....
      ...AAxAAAAxAA...
      ...AAkAAAAkAA...
      ....AAWPPWAA....
      .....AWWWWA.....
      .....AAWWAA.....
      .....AAAAAA..A..
      .....WA..AW..A..
    `), tpl(`
      @5
      ....A......A....
      ....AA....AA....
      ....APAAAAPA....
      ...AAxAAAAxAA...
      ...AAkAAAAkAA...
      ....AAWPPWAA....
      .....AWWWWA.....
      .....AAWWAA.....
      .....AAAAAA..A..
      .....WA...A..A..
    `)],
    left: [tpl(`
      @8
      ...A.A..........
      ...AAAA.......A.
      ..AkAAA.......A.
      .PAAAAxAxAxAAA..
      ..WWAAAAAAAAAa..
      ...AA.A...A.Aa..
      ...WW.W...W.WW..
    `), tpl(`
      @8
      ...A.A..........
      ...AAAA......A..
      ..AkAAA.......A.
      .PAAAAxAxAxAAA..
      ..WWAAAAAAAAAa..
      ....AA.A.A..A...
      ....W..W.W..W...
    `)],
    up: [tpl(`
      @5
      ....A......A....
      ....AA....AA....
      ....AAAAAAAA....
      ...AAAAxxAAAA...
      ...AAAAAAAAAA...
      ....aAAAAAAa....
      .....AAxxAA.....
      .....AAAAAA.....
      .....AAxxAA.....
      .....AA..AA.....
    `), tpl(`
      @5
      ....A......A....
      ....AA....AA....
      ....AAAAAAAA....
      ...AAAAxxAAAA...
      ...AAAAAAAAAA...
      ....aAAAAAAa....
      .....AAxxAA.....
      .....AAAAAA.....
      .....AAxxAA.....
      .....AA..WW.....
    `)],
  };
  L.cat_tail = {
    up: [tpl(`
      @8
      .............A..
      .............A..
      ............A...
      ...........A....
    `), tpl(`
      @8
      ..A.............
      ..A.............
      ...A............
      ....A...........
    `)],
  };

  const coffinV = tpl(`
      @2
      .....LLLLLL.....
      ....LTTTTTTt....
      ...LTTTTTTTTt...
      ...LTTTGGTTTt...
      ...LTTGGGGTTt...
      ...LTTTGGTTTt...
      ...LTTTGGTTTt...
      ...LTTTggTTTt...
      ....LTTTTTTt....
      ....LTTTTTTt....
      .....LTTTTt.....
      .....LTTTTt.....
      .....tttttt.....
  `);
  const coffinH = tpl(`
      @8
      ...LLLLLLLLLL...
      ..LTTGTTTTTTTt..
      .LTTGGGGGGTTTTt.
      ..LTTGTTTTTTTt..
      ..tttttttttttt..
      ..tttttttttttt..
      ...tttttttttt...
  `);
  L.coffin = {
    down: [coffinV, shift(coffinV, 0, -1)],
    left: [coffinH, shift(coffinH, 0, -1)],
    up: [coffinV, shift(coffinV, 0, -1)],
  };

  // ---------------------------------------------------------------------------
  // Kinds.  pal: palette letters -> colours (merged over DEFAULT_PAL).
  // parts: list of parts drawn in order; a part is a list of layer names, or
  // { l: [names], ol: false } for an un-outlined fix-up layer (e.g. a hand
  // gripping a staff), or { l: [names], shift: { dir: [dx, dy] } }.
  // Layers missing for a direction are skipped (e.g. 'staff_b' only exists for
  // down/up where the staff is behind the body; 'staff_f' only for left).
  // ---------------------------------------------------------------------------
  const DEFAULT_PAL = {
    S: P.skin, s: P.skinS, L: P.skinL,
    W: P.white, w: P.grey1,
    G: P.gold, g: P.goldS,
    M: P.grey1, m: P.grey2, n: P.grey3,
    T: P.brown, t: P.brownS,
    R: P.red, r: P.redS,
    J: P.blue, X: P.blueL, x: P.blueS,
    C: P.brownS, D: P.brownS, d: P.brownD,
  };
  const mix = (...o) => Object.assign({}, ...o);
  // lighten a #rrggbb colour toward white by t (0..1)
  function lighten(hex, t) {
    const v = parseInt(hex.slice(1), 16);
    const ch = s => Math.round(((v >> s) & 255) + (255 - ((v >> s) & 255)) * t);
    return '#' + ((1 << 24) | (ch(16) << 16) | (ch(8) << 8) | ch(0)).toString(16).slice(1);
  }
  const cloth = (A, a, Y) => ({ A, a, Y: Y || lighten(A, 0.3) });

  const KINDS = {
    // ---- party ----------------------------------------------------------------
    hero_m: {
      pal: mix(HAIR_C.chestnut, cloth('#30a8c0', '#1c6c88'), { E: P.red, e: P.redS, B: '#e8d0a0', b: '#b89868', C: P.brownS, D: P.brownS, d: P.brownD, T: P.brownS, m: P.grey2 }),
      parts: [['tunic'], ['face', 'hero_hair_m'], ['hilt']],
    },
    hero_f: {
      pal: mix(HAIR_C.chestnut, cloth('#30a8c0', '#1c6c88'), { E: P.red, e: P.redS, B: '#e8d0a0', b: '#b89868', C: P.brownS, D: P.brownS, d: P.brownD, T: P.brownS, m: P.grey2 }),
      parts: [['skirt'], ['face', 'hero_hair_f'], ['hilt']],
    },
    warrior_m: {
      pal: mix(HAIR_C.brown, { M: P.grey1, m: P.grey2, n: P.grey3, W: P.white, B: P.blue, b: P.blueS, R: P.red, r: P.redS }),
      parts: [['armor'], ['face', 'hair_short', 'helmet_crest']],
    },
    warrior_f: {
      pal: mix(HAIR_C.orange, { M: P.grey1, m: P.grey2, n: P.grey3, W: P.white, B: P.blue, b: P.blueS, R: P.red, r: P.redS }),
      parts: [['armor_f'], ['face', 'hair_long', 'helmet_crest']],
    },
    fighter_m: {
      pal: mix(HAIR_C.black, cloth(P.orange, '#c86818'), { B: P.orange, b: '#c86818', C: '#302838', D: '#302838', d: '#201820', E: P.white, e: P.grey1 }),
      parts: [['tunic', 'gi'], ['face', 'hair_short', 'headband']],
    },
    fighter_f: {
      pal: mix(HAIR_C.black, cloth(P.red, P.redS), { B: P.red, b: P.redS, C: '#302838', D: '#302838', d: '#201820', E: P.white, e: P.grey1 }),
      parts: [['tunic', 'gi'], ['face', 'hair_buns', 'headband']],
    },
    priest_m: {
      pal: mix(HAIR_C.brown, cloth(P.white, P.grey1), { V: P.blue, E: P.white, e: P.grey1, F: P.blue, f: P.blueS, D: P.blueS }),
      parts: [['robe', 'stole'], ['face', 'hair_short', 'mitre']],
    },
    priest_f: {
      pal: mix(cloth(P.white, P.grey1), { E: P.blue, e: P.blueS, W: P.white, V: P.blue, D: P.blueS }),
      parts: [['dress', 'stole'], ['face', 'hood']],
    },
    mage_m: {
      pal: mix(HAIR_C.dbrown, cloth(P.purple, P.purpleS), { E: P.purple, e: P.purpleS, F: P.gold, f: P.goldS, C: P.gold, D: P.purpleS, T: P.brown, t: P.brownS, X: '#f84868', x: '#a81838' }),
      parts: [['staff_b'], ['robe', 'robe_trim'], ['face', 'hair_short', 'witch_hat'], ['staff_f'], { l: ['grip'], ol: false }],
    },
    mage_f: {
      pal: mix(HAIR_C.pink, cloth('#b02848', '#701830'), { E: '#383048', e: '#201828', F: '#b02848', f: '#701830', C: P.gold, D: '#383048', T: P.brown, t: P.brownS, X: '#58d8f8', x: '#1878b0' }),
      parts: [['staff_b'], ['robe', 'robe_trim'], ['face', 'hair_long', 'witch_hat'], ['staff_f'], { l: ['grip'], ol: false }],
    },
    merchant_m: {
      pal: mix(HAIR_C.brown, cloth('#f0e0c0', '#c0a878'), { V: P.brown, v: P.brownS, E: P.green, e: P.greenS, F: '#90e078', B: P.brownS, C: P.brownD, O: '#e8d8b0', o: '#b8a070', P: P.brown, p: P.brownS }),
      parts: [['pack_back'], ['tunic', 'vest', 'pack_straps'], ['pack_over'], ['face', 'hair_short', 'turban']],
    },
    merchant_f: {
      pal: mix(HAIR_C.dbrown, cloth('#e05848', '#a83028'), { V: P.white, v: P.grey1, E: P.gold, e: P.goldS, D: P.brownS, O: '#f0e0b8', o: '#c0a878', P: '#d8a860', p: '#a07038', C: P.brownS }),
      parts: [['pack_back'], ['dress', 'apron', 'pack_straps'], ['pack_over'], ['face', 'hair_long', 'bandana']],
    },
    jester_m: {
      pal: mix(cloth(P.red, P.redS), { R: P.red, X: P.blue, G: P.gold, E: P.red, e: P.redS, F: P.blue, f: P.blueS, B: P.blue, b: P.blueS, C: P.gold, D: P.purpleS }),
      parts: [['tunic', 'motley', 'ruff'], ['face', 'jester_hat']],
    },
    jester_f: {
      pal: mix(HAIR_C.blond, cloth('#e040a0', '#a01870'), { R: '#e040a0', X: '#30c8d0', G: P.gold, E: P.white, e: P.grey1, F: P.pink, B: '#30c8d0', b: '#188890', C: P.gold, D: '#a01870' }),
      parts: [['skirt', 'motley_skirt', 'ruff'], ['face', 'hair_long', 'bunny_ears']],
    },

    // ---- NPCs -----------------------------------------------------------------
    king: {
      pal: mix(HAIR_C.white, cloth(P.red, P.redS), { W: P.white, w: P.grey1, D: P.redS, R: P.red }),
      parts: [['robe', 'fur_collar'], ['face', 'hair_short', 'beard', 'crown']],
    },
    queen: {
      pal: mix(HAIR_C.blond, cloth(P.purple, P.purpleS, '#b080e0'), { J: P.blue }),
      parts: [['gown'], ['face', 'hair_long', 'tiara']],
    },
    princess: {
      pal: mix(HAIR_C.pink, cloth('#e04888', '#a02060', '#f878b0'), { J: P.red, W: P.white }),
      parts: [['gown'], ['face', 'hair_long', 'tiara_small']],
    },
    minister: {
      pal: mix(HAIR_C.grey, cloth('#6848a8', '#402870'), { C: P.gold, D: '#402870' }),
      parts: [['robe', 'robe_trim'], ['face', 'hair_bald', 'mustache']],
    },
    soldier: {
      pal: { M: P.grey1, m: P.grey2, n: P.grey3, W: P.white, B: P.grey2, b: P.grey3, V: P.blue, v: P.blueS, G: P.gold, T: P.brown, t: P.brownS, R: P.red },
      parts: [['spear_b'], ['armor', 'tabard'], ['face', 'helmet_nose'], ['spear_f'], { l: ['grip_armor'], ol: false }],
    },
    man: {
      pal: mix(HAIR_C.brown, cloth('#38a040', '#1c6428'), { B: P.brownS, C: P.brownD, D: P.brownD, d: '#301808' }),
      parts: [['tunic'], ['face', 'hair_short']],
    },
    man2: {
      pal: mix(HAIR_C.blond, cloth(P.red, P.redS), { B: '#405080', b: '#283058', C: P.brownD, D: P.brownD, d: '#301808' }),
      parts: [['tunic'], ['face', 'hair_swept']],
    },
    woman: {
      pal: mix(HAIR_C.dbrown, cloth(P.blue, P.blueS), { D: P.brownS }),
      parts: [['dress'], ['face', 'hair_long']],
    },
    woman2: {
      pal: mix(HAIR_C.ginger, cloth('#40a060', '#1c6438'), { D: P.brownS }),
      parts: [['dress'], ['face', 'hair_bun']],
    },
    oldman: {
      pal: mix(HAIR_C.white, cloth(P.brown, P.brownS), { D: P.brownD, T: '#e0b070', t: '#a07038' }),
      parts: [['cane_b'], ['robe'], ['face', 'hair_bald', 'beard'], ['cane_f'], { l: ['grip1'], ol: false }],
    },
    oldwoman: {
      pal: mix(HAIR_C.grey, cloth('#706070', '#483848'), { V: P.purple, v: P.purpleS, D: P.brownD }),
      parts: [['dress', 'shawl'], { l: ['face', 'hair_bun'], shift: { down: [0, 2], left: [-1, 2], up: [0, 2] } }],
    },
    boy: {
      pal: mix(HAIR_C.orange, { A: P.white, a: P.grey1, B: P.blue, b: P.blueS, D: P.brownS }),
      parts: [['kid_overalls'], ['face_kid', 'hair_kid_messy']],
    },
    girl: {
      pal: mix(HAIR_C.dbrown, cloth(P.gold, P.goldS), { R: P.red, D: P.red }),
      parts: [['kid_dress'], ['face_kid', 'hair_kid_pigtails']],
    },
    mother: {
      pal: mix(HAIR_C.dbrown, cloth('#e87890', '#b04860'), { V: P.white, v: P.grey1, D: P.brownS }),
      parts: [['dress', 'apron'], ['face', 'hair_bun']],
    },
    hostess: {
      pal: mix(HAIR_C.red, cloth('#10988c', '#085850'), { D: '#085850', J: P.red }),
      parts: [['dress', 'necklace'], ['face', 'hair_wavy']],
    },
    innkeeper: {
      pal: mix(HAIR_C.brown, cloth('#90c0f8', '#5890d0'), { V: P.white, v: P.grey1, B: P.brownS, b: P.brownD, D: P.brownD }),
      parts: [['plump', 'apron'], ['face', 'hair_short', 'mustache']],
    },
    shopkeeper: {
      pal: mix(HAIR_C.dbrown, cloth('#e8d8b0', '#b8a070'), { V: P.brown, v: P.brownS, C: P.brown, B: P.brownS, b: P.brownD, D: P.brownD, E: '#3058a8', e: '#1c3470', F: '#4870c0' }),
      parts: [['burly', 'apron'], ['face', 'hair_short', 'mustache', 'bandana']],
    },
    priest_npc: {
      pal: mix(HAIR_C.grey, cloth(P.white, P.grey1), { V: P.gold, E: P.white, e: P.grey1, F: P.gold, f: P.goldS, G: P.red, D: P.goldS }),
      parts: [['robe', 'stole'], ['face', 'hair_short', 'mitre']],
    },
    nun: {
      pal: mix(cloth('#383048', '#201828'), { E: '#383048', e: '#201828', F: '#6c6488', W: P.white, D: '#201828' }),
      parts: [['dress'], ['face', 'veil']],
    },
    sage: {
      pal: mix(cloth('#a8b0a0', '#707868'), { E: '#a8b0a0', e: '#707868', W: P.white, w: P.grey1, D: '#505848', T: '#8c5428', t: '#5c3014' }),
      parts: [['sage_staff_b'], ['robe'], ['face', 'hood_pointed', 'beard_long'], ['sage_staff_f'], { l: ['grip'], ol: false }],
    },
    bomber: {
      pal: mix(HAIR_C.white, cloth('#e8d8b0', '#b8a070'), { V: P.brown, v: P.brownS, B: P.brown, b: P.brownS, C: P.brown, D: P.brownD, d: '#301808', X: P.blueL, x: P.blue }),
      parts: [['tunic', 'overalls', 'soot'], ['face', 'hair_wild', 'mustache_small']],
    },
    collector: {
      pal: mix(HAIR_C.white, cloth(P.blue, P.blueS), { E: '#6040b0', e: '#3c2478', G: P.gold, W: P.white, D: P.blueS }),
      parts: [['robe'], ['face', 'mustache_small', 'nightcap']],
    },
    bard: {
      pal: mix(HAIR_C.blond, cloth('#e8a030', '#b06818'), { R: P.green, r: P.greenS, E: '#c83040', e: '#801828', F: P.white, f: P.grey1, B: P.brownS, C: P.brownD, D: P.brownD, T: '#c88848', t: '#7c4820' }),
      parts: [['cape_back', 'lute_back'], ['tunic'], ['cape_over', 'lute_over'], ['face', 'hair_short', 'feather_cap']],
    },
    sailor: {
      pal: mix(HAIR_C.black, cloth(P.white, P.grey1), { F: P.blue, B: '#283870', b: '#182048', C: '#283870', D: P.brownD, E: P.red, e: P.redS }),
      parts: [['tunic', 'stripes'], ['face', 'hair_short', 'bandana']],
    },
    thief: {
      pal: mix(cloth('#9858d0', '#603098'), { E: '#585870', e: '#383850', I: '#8080a0', F: '#403858', B: '#483060', b: '#302040', C: '#2c2838', D: '#2c2838', d: '#1c1824' }),
      parts: [['tunic'], ['face', 'thief_hood']],
    },
    ghost: {
      pal: { W: P.white, w: '#b8c0e0' },
      parts: [['ghost']],
    },
    dark_knight: {
      pal: { M: '#7c5c9c', m: '#4c3464', n: '#2c1c3c', W: '#a888d0', B: '#3c2850', b: '#281a38', C: '#2c1c3c', N: '#4c3464', O: '#e8e0c8', Q: '#ff3030', R: '#a01828', r: '#600818', S: '#4c3464' },
      parts: [['cape_back'], ['armor', 'spikes'], ['cape_over'], ['helmet_horns']],
    },
    dog: {
      pal: { A: '#c88040', a: '#905828', E: '#704018', W: '#f0e0c0' },
      parts: [['dog'], ['dog_tail']],
    },
    cat: {
      pal: { A: '#f8a048', a: '#c06820', x: '#c06820', W: P.white, P: P.pink },
      parts: [['cat'], ['cat_tail']],
    },
    coffin: {
      pal: { L: '#d89858', T: '#a86830', t: '#684020', G: P.gold, g: P.goldS },
      parts: [['coffin']],
    },
  };

  // ---------------------------------------------------------------------------
  function layer(name, dir, frame) {
    const e = L[name];
    if (!e) throw new Error('unknown layer ' + name);
    const v = e[dir];
    if (!v) return null;
    return typeof v[0] === 'string' ? v : v[frame];
  }

  function build(kind, dir, frame) {
    const k = KINDS[kind];
    const pal = mix(DEFAULT_PAL, k.pal);
    const baseDir = dir === 'right' ? 'left' : dir;
    const parts = [];
    for (const p of k.parts) {
      const spec = Array.isArray(p) ? { l: p } : p;
      const sh = spec.shift && spec.shift[baseDir];
      const t = spec.l.map(n => layer(n, baseDir, frame)).filter(Boolean).map(tt => sh ? shift(tt, sh[0], sh[1]) : tt);
      if (t.length) parts.push({ t, ol: spec.ol });
    }
    let pix = renderParts(parts, pal);
    if (dir === 'right') {
      const m = new Array(256);
      for (let i = 0; i < 256; i++) m[i] = pix[(i & ~15) + (15 - (i & 15))];
      pix = m;
    }
    return pix;
  }

  const DIRS = ['down', 'left', 'up', 'right'];
  const cache = new Map();
  function get(kind, dir, frame) {
    if (typeof kind !== 'string' || !Object.prototype.hasOwnProperty.call(KINDS, kind)) kind = 'man';
    if (DIRS.indexOf(dir) < 0) dir = 'down';
    frame = (Number(frame) || 0) & 1;
    const key = kind + '|' + dir + '|' + frame;
    let c = cache.get(key);
    if (c) return c;
    try {
      c = toCanvas(build(kind, dir, frame));
    } catch (e) {
      if (typeof console !== 'undefined') console.error('CharArt: failed to build ' + key + ': ' + (e && e.message));
      if (kind !== 'man') c = get('man', dir, frame);
      else {
        try { c = toCanvas(new Array(256).fill(null)); } catch (e2) { c = null; }
      }
    }
    if (c) cache.set(key, c);
    return c;
  }

  if (badTemplates.length && typeof console !== 'undefined') console.error('CharArt: bad template rows:\n' + badTemplates.join('\n'));

  return { get, kinds: Object.keys(KINDS) };
})();
