window.__SEED__ = {
  "people": [
    {
      "id": "p_koyama",
      "name": "小山",
      "color": "#4f86f7",
      "memo": "",
      "active": true
    },
    {
      "id": "p_hosogaya",
      "name": "細萱",
      "color": "#e07a3c",
      "memo": "",
      "active": true
    },
    {
      "id": "p_yamaguchi",
      "name": "山口",
      "color": "#1aaa6b",
      "memo": "",
      "active": true
    },
    {
      "id": "p_kaneko",
      "name": "金子",
      "color": "#c2569a",
      "memo": "",
      "active": true
    },
    {
      "id": "p_wakayama",
      "name": "若山",
      "color": "#8a6ad8",
      "memo": "",
      "active": true
    },
    {
      "id": "p_yamamoto",
      "name": "山本",
      "color": "#d4a017",
      "memo": "",
      "active": true
    }
  ],
  "customers": [
    {
      "id": "c_1",
      "name": "LED　PJ",
      "memo": ""
    },
    {
      "id": "c_2",
      "name": "TOHOシネマズ",
      "memo": ""
    },
    {
      "id": "c_3",
      "name": "ニッパツ",
      "memo": ""
    },
    {
      "id": "c_4",
      "name": "ユナイテッドシネマ",
      "memo": ""
    },
    {
      "id": "c_5",
      "name": "佐々木興業",
      "memo": ""
    },
    {
      "id": "c_6",
      "name": "山本さん",
      "memo": ""
    },
    {
      "id": "c_7",
      "name": "東急レクリエーション",
      "memo": ""
    }
  ],
  "projects": [
    {
      "id": "CP0001",
      "customer": "TOHOシネマズ",
      "name": "TOHO市川　熱源+空調換気更新　1期",
      "inquiryDate": "2025-10-14",
      "submitDate": "2025-09-15",
      "quoteType": "納期確認",
      "caseStatus": "受注",
      "orderTargetDate": "2025-09-15",
      "completionTargetDate": "2026-02-01",
      "quoteAmountCurrent": 87500000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 87500000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 65625000,
      "costRate": 0.75,
      "expectedGrossProfit": 21875000,
      "progress": "工事中",
      "leader": "金子",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.2,
        "山口": 0.05,
        "金子": 0.4,
        "若山": 0.05,
        "山本": 0.05
      }
    },
    {
      "id": "CP0002",
      "customer": "TOHOシネマズ",
      "name": "TOHO市川　熱源+空調換気更新　2期",
      "inquiryDate": null,
      "submitDate": "2025-09-15",
      "quoteType": "納期確認",
      "caseStatus": "受注",
      "orderTargetDate": "2026-01-01",
      "completionTargetDate": "2026-05-01",
      "quoteAmountCurrent": 112000000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 112000000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 84000000,
      "costRate": 0.75,
      "expectedGrossProfit": 28000000,
      "progress": "工事中",
      "leader": "金子",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.2,
        "山口": 0.05,
        "金子": 0.4,
        "若山": 0.05,
        "山本": 0.05
      }
    },
    {
      "id": "CP0003",
      "customer": "TOHOシネマズ",
      "name": "横浜　事務所系統空調機更新",
      "inquiryDate": null,
      "submitDate": "2025-06-10",
      "quoteType": "納期確認",
      "caseStatus": "見積",
      "orderTargetDate": "2026-03-01",
      "completionTargetDate": "2026-06-01",
      "quoteAmountCurrent": 8600000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 8600000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 6450000,
      "costRate": 0.75,
      "expectedGrossProfit": 2150000,
      "progress": "見積提出済",
      "leader": "金子",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.2,
        "山口": 0.05,
        "金子": 0.4,
        "若山": 0.05,
        "山本": 0.05
      }
    },
    {
      "id": "CP0004",
      "customer": "TOHOシネマズ",
      "name": "池袋　コンセッション増設",
      "inquiryDate": null,
      "submitDate": "2025-09-26",
      "quoteType": "小口",
      "caseStatus": "見積",
      "orderTargetDate": "2026-01-01",
      "completionTargetDate": "2026-02-01",
      "quoteAmountCurrent": 2460000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 2460000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 1845000,
      "costRate": 0.75,
      "expectedGrossProfit": 615000,
      "progress": "竣工",
      "leader": "金子",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.2,
        "山口": 0.05,
        "金子": 0.4,
        "若山": 0.05,
        "山本": 0.05
      }
    },
    {
      "id": "CP0005",
      "customer": "TOHOシネマズ",
      "name": "新宿　コンセッション増設",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2026-03-01",
      "completionTargetDate": "2026-06-01",
      "quoteAmountCurrent": 4000000,
      "orderJudge": "◎",
      "judgedAmountCurrent": 3200000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 2400000,
      "costRate": 0.75,
      "expectedGrossProfit": 800000,
      "progress": "基本計画作成中",
      "leader": "金子→小山",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.2,
        "山口": 0.05,
        "金子": 0.4,
        "若山": 0.05,
        "山本": 0.05
      }
    },
    {
      "id": "CP0006",
      "customer": "TOHOシネマズ",
      "name": "西新井　コンセッション改善",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2026-03-01",
      "completionTargetDate": "2026-06-01",
      "quoteAmountCurrent": 4000000,
      "orderJudge": "○",
      "judgedAmountCurrent": 2400000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 1800000,
      "costRate": 0.75,
      "expectedGrossProfit": 600000,
      "progress": "見積提出済",
      "leader": "小山",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.2,
        "山口": 0.05,
        "金子": 0.4,
        "若山": 0.05,
        "山本": 0.05
      }
    },
    {
      "id": "CP0007",
      "customer": "TOHOシネマズ",
      "name": "くずは　シアター系統更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2027-12-01",
      "completionTargetDate": "2028-06-01",
      "quoteAmountCurrent": 200000000,
      "orderJudge": "-",
      "judgedAmountCurrent": 0,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 0,
      "costRate": null,
      "expectedGrossProfit": 0,
      "progress": "基本計画作成中",
      "leader": "小山",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.2,
        "山口": 0.05,
        "金子": 0.4,
        "若山": 0.05,
        "山本": 0.05
      }
    },
    {
      "id": "CP0008",
      "customer": "TOHOシネマズ",
      "name": "宇都宮　コンセ系統増設　【概算】",
      "inquiryDate": null,
      "submitDate": "2025-12-19",
      "quoteType": "小口",
      "caseStatus": "受注",
      "orderTargetDate": "2026-03-01",
      "completionTargetDate": "2027-02-01",
      "quoteAmountCurrent": 0,
      "orderJudge": "来期",
      "judgedAmountCurrent": null,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": null,
      "costRate": null,
      "expectedGrossProfit": null,
      "progress": "見積提出済",
      "leader": "小山",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.25,
        "山口": 0.05,
        "金子": 0.4,
        "若山": 0.05
      }
    },
    {
      "id": "CP0009",
      "customer": "TOHOシネマズ",
      "name": "各店保守　来期",
      "inquiryDate": null,
      "submitDate": "2025-12-19",
      "quoteType": "納期確認",
      "caseStatus": "受注",
      "orderTargetDate": "2026-03-01",
      "completionTargetDate": "2027-02-01",
      "quoteAmountCurrent": 18373500,
      "orderJudge": "来期",
      "judgedAmountCurrent": 0,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": null,
      "costRate": null,
      "expectedGrossProfit": null,
      "progress": "工事中",
      "leader": "金子",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.25,
        "山口": 0.05,
        "金子": 0.4,
        "若山": 0.05
      }
    },
    {
      "id": "CP0010",
      "customer": "東急レクリエーション",
      "name": "木場　チラー更新",
      "inquiryDate": null,
      "submitDate": "2025-09-25",
      "quoteType": "納期確認",
      "caseStatus": "受注",
      "orderTargetDate": "2025-10-15",
      "completionTargetDate": "2026-07-15",
      "quoteAmountCurrent": 35000000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 35000000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 27800000,
      "costRate": 0.7942857142857143,
      "expectedGrossProfit": 7200000,
      "progress": "着工前調整中",
      "leader": "細萱",
      "allocations": {
        "小山": 0.2,
        "細萱": 0.4,
        "山口": 0.2,
        "金子": 0.05,
        "若山": 0.1,
        "山本": 0.05
      }
    },
    {
      "id": "CP0011",
      "customer": "東急レクリエーション",
      "name": "南町田　シアター系統更新",
      "inquiryDate": null,
      "submitDate": "2025-09-25",
      "quoteType": "納期確認",
      "caseStatus": "受注",
      "orderTargetDate": "2025-10-15",
      "completionTargetDate": "2026-06-01",
      "quoteAmountCurrent": 265000000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 265000000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 208300000,
      "costRate": 0.7860377358490566,
      "expectedGrossProfit": 56700000,
      "progress": "工事中",
      "leader": "細萱",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.25,
        "山口": 0.2,
        "金子": 0.05,
        "若山": 0.2,
        "山本": 0.05
      }
    },
    {
      "id": "CP0012",
      "customer": "東急レクリエーション",
      "name": "川崎　GHP更新計画　3系統(1,6,7)、ぐっぴー6月",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2026-04-27",
      "completionTargetDate": "2026-09-05",
      "quoteAmountCurrent": 100000000,
      "orderJudge": "△",
      "judgedAmountCurrent": 30000000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 22500000,
      "costRate": 0.75,
      "expectedGrossProfit": 7500000,
      "progress": "積算中",
      "leader": "小山",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.3,
        "山口": 0.25,
        "金子": 0.05,
        "若山": 0.1,
        "山本": 0.05
      }
    },
    {
      "id": "CP0013",
      "customer": "東急レクリエーション",
      "name": "南町田　一般系統更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "受注",
      "orderTargetDate": "2025-09-16",
      "completionTargetDate": "2025-12-16",
      "quoteAmountCurrent": 30000000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 30000000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 22500000,
      "costRate": 0.75,
      "expectedGrossProfit": 7500000,
      "progress": "竣工",
      "leader": "山口",
      "allocations": {
        "小山": 0.1,
        "細萱": 0.1,
        "山口": 0.55,
        "金子": 0.05,
        "若山": 0.2
      }
    },
    {
      "id": "CP0014",
      "customer": "東急レクリエーション",
      "name": "神戸　コリドー系統更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "小口",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": null,
      "orderJudge": "",
      "judgedAmountCurrent": null,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": null,
      "costRate": null,
      "expectedGrossProfit": null,
      "progress": "積算中",
      "leader": "細萱",
      "allocations": {}
    },
    {
      "id": "CP0015",
      "customer": "東急レクリエーション",
      "name": "HAT神戸　全台更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 300000000,
      "orderJudge": "-",
      "judgedAmountCurrent": 0,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 0,
      "costRate": null,
      "expectedGrossProfit": 0,
      "progress": "見積提出済",
      "leader": "細萱",
      "allocations": {}
    },
    {
      "id": "CP0016",
      "customer": "東急レクリエーション",
      "name": "神戸　コンセ更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 10800000,
      "orderJudge": "-",
      "judgedAmountCurrent": 0,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 0,
      "costRate": null,
      "expectedGrossProfit": 0,
      "progress": "見積提出済",
      "leader": "細萱",
      "allocations": {}
    },
    {
      "id": "CP0017",
      "customer": "東急レクリエーション",
      "name": "神戸　映写室更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "小口",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": null,
      "orderJudge": "-",
      "judgedAmountCurrent": null,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": null,
      "costRate": null,
      "expectedGrossProfit": null,
      "progress": "積算中",
      "leader": "細萱",
      "allocations": {}
    },
    {
      "id": "CP0018",
      "customer": "東急レクリエーション",
      "name": "箕面　シアター系統更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "見積",
      "orderTargetDate": "2026-02-16",
      "completionTargetDate": "2026-10-01",
      "quoteAmountCurrent": 168000000,
      "orderJudge": "△",
      "judgedAmountCurrent": 50400000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 37800000,
      "costRate": 0.75,
      "expectedGrossProfit": 12600000,
      "progress": "積算中",
      "leader": "細萱",
      "allocations": {}
    },
    {
      "id": "CP0019",
      "customer": "東急レクリエーション",
      "name": "港北　5階映写室系統更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2026-04-16",
      "completionTargetDate": "2026-06-01",
      "quoteAmountCurrent": 4500000,
      "orderJudge": "△",
      "judgedAmountCurrent": 1350000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 1012500,
      "costRate": 0.75,
      "expectedGrossProfit": 337500,
      "progress": "見積提出済",
      "leader": "山口",
      "allocations": {
        "小山": 0.15,
        "細萱": 0.15,
        "山口": 0.4,
        "金子": 0.05,
        "若山": 0.25
      }
    },
    {
      "id": "CP0020",
      "customer": "東急レクリエーション",
      "name": "名古屋　コリドー系統更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2026-02-16",
      "completionTargetDate": "2026-06-01",
      "quoteAmountCurrent": 10800000,
      "orderJudge": "◎",
      "judgedAmountCurrent": 8640000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 6480000,
      "costRate": 0.75,
      "expectedGrossProfit": 2160000,
      "progress": "見積提出済",
      "leader": "小山",
      "allocations": {
        "小山": 0.15,
        "細萱": 0.15,
        "山口": 0.4,
        "金子": 0.05,
        "若山": 0.25
      }
    },
    {
      "id": "CP0021",
      "customer": "東急レクリエーション",
      "name": "2026年109各店保守契約",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 45000000,
      "orderJudge": "来期",
      "judgedAmountCurrent": 0,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": null,
      "costRate": null,
      "expectedGrossProfit": null,
      "progress": "",
      "leader": "若山",
      "allocations": {
        "小山": 0.15,
        "細萱": 0.15,
        "山口": 0.25,
        "金子": 0.05,
        "若山": 0.4
      }
    },
    {
      "id": "CP0022",
      "customer": "ユナイテッドシネマ",
      "name": "つくば　シアター8更新【閉館】",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "見積",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 35000000,
      "orderJudge": "-",
      "judgedAmountCurrent": 0,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": null,
      "costRate": null,
      "expectedGrossProfit": null,
      "progress": "",
      "leader": "山口",
      "allocations": {
        "小山": 0.15,
        "細萱": 0.15,
        "山口": 0.4,
        "金子": 0.05,
        "若山": 0.25
      }
    },
    {
      "id": "CP0023",
      "customer": "ユナイテッドシネマ",
      "name": "わかば　映写室系統更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "受注",
      "orderTargetDate": "2026-01-16",
      "completionTargetDate": "2026-02-16",
      "quoteAmountCurrent": 3800000,
      "orderJudge": "◎",
      "judgedAmountCurrent": 3040000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 2280000,
      "costRate": 0.75,
      "expectedGrossProfit": 760000,
      "progress": "竣工",
      "leader": "若山",
      "allocations": {
        "小山": 0.15,
        "細萱": 0.15,
        "山口": 0.25,
        "金子": 0.05,
        "若山": 0.4
      }
    },
    {
      "id": "CP0024",
      "customer": "ユナイテッドシネマ",
      "name": "前橋　トレーサー更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2026-03-27",
      "completionTargetDate": "2026-07-27",
      "quoteAmountCurrent": 6400000,
      "orderJudge": "○",
      "judgedAmountCurrent": 3840000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 2880000,
      "costRate": 0.75,
      "expectedGrossProfit": 960000,
      "progress": "見積提出済",
      "leader": "山口",
      "allocations": {
        "小山": 0.15,
        "細萱": 0.15,
        "山口": 0.4,
        "金子": 0.05,
        "若山": 0.25
      }
    },
    {
      "id": "CP0025",
      "customer": "ユナイテッドシネマ",
      "name": "としまえん　シアター系統更新　2シアター分",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2026-03-27",
      "completionTargetDate": "2026-07-27",
      "quoteAmountCurrent": 88000000,
      "orderJudge": "○",
      "judgedAmountCurrent": 52800000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 39600000,
      "costRate": 0.75,
      "expectedGrossProfit": 13200000,
      "progress": "見積提出済",
      "leader": "山口",
      "allocations": {
        "小山": 0.15,
        "細萱": 0.15,
        "山口": 0.25,
        "金子": 0.05,
        "若山": 0.4
      }
    },
    {
      "id": "CP0026",
      "customer": "ユナイテッドシネマ",
      "name": "としまえん　中央監視更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "見積",
      "orderTargetDate": "2026-03-27",
      "completionTargetDate": "2026-07-27",
      "quoteAmountCurrent": 17000000,
      "orderJudge": "○",
      "judgedAmountCurrent": 10200000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 7650000,
      "costRate": 0.75,
      "expectedGrossProfit": 2550000,
      "progress": "見積提出済",
      "leader": "小山",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.15,
        "山口": 0.4,
        "金子": 0.05,
        "若山": 0.15
      }
    },
    {
      "id": "CP0027",
      "customer": "ユナイテッドシネマ",
      "name": "豊洲　シアター系統更新　2シアター分",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2026-03-27",
      "completionTargetDate": "2026-09-27",
      "quoteAmountCurrent": 75000000,
      "orderJudge": "○",
      "judgedAmountCurrent": 45000000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 33750000,
      "costRate": 0.75,
      "expectedGrossProfit": 11250000,
      "progress": "見積提出済",
      "leader": "山口",
      "allocations": {
        "小山": 0.15,
        "細萱": 0.15,
        "山口": 0.4,
        "金子": 0.05,
        "若山": 0.25
      }
    },
    {
      "id": "CP0028",
      "customer": "ユナイテッドシネマ",
      "name": "金沢　シアター系統更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "見積",
      "orderTargetDate": "2026-02-27",
      "completionTargetDate": "2026-06-27",
      "quoteAmountCurrent": 180500000,
      "orderJudge": "○",
      "judgedAmountCurrent": 108300000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 81225000,
      "costRate": 0.75,
      "expectedGrossProfit": 27075000,
      "progress": "見積提出済",
      "leader": "小山",
      "allocations": {}
    },
    {
      "id": "CP0029",
      "customer": "ユナイテッドシネマ",
      "name": "金沢　一般更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "見積",
      "orderTargetDate": "2026-02-27",
      "completionTargetDate": "2026-06-27",
      "quoteAmountCurrent": 5600000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 5600000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 4200000,
      "costRate": 0.75,
      "expectedGrossProfit": 1400000,
      "progress": "着工前調整中",
      "leader": "小山",
      "allocations": {}
    },
    {
      "id": "CP0030",
      "customer": "ユナイテッドシネマ",
      "name": "幸手　シアター9系統更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2026-02-27",
      "completionTargetDate": "2026-06-27",
      "quoteAmountCurrent": 26000000,
      "orderJudge": "△",
      "judgedAmountCurrent": 7800000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 5850000,
      "costRate": 0.75,
      "expectedGrossProfit": 1950000,
      "progress": "見積提出済",
      "leader": "山口",
      "allocations": {}
    },
    {
      "id": "CP0031",
      "customer": "ユナイテッドシネマ",
      "name": "幸手　フィットネスジム更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2026-02-27",
      "completionTargetDate": "2026-06-27",
      "quoteAmountCurrent": 13000000,
      "orderJudge": "◎",
      "judgedAmountCurrent": 10400000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 7800000,
      "costRate": 0.75,
      "expectedGrossProfit": 2600000,
      "progress": "見積作成中",
      "leader": "山口",
      "allocations": {}
    },
    {
      "id": "CP0032",
      "customer": "ユナイテッドシネマ",
      "name": "来期　幸手　シアター系統更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "小口",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": null,
      "orderJudge": "来期",
      "judgedAmountCurrent": null,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": null,
      "costRate": null,
      "expectedGrossProfit": null,
      "progress": "",
      "leader": "仮細萱",
      "allocations": {}
    },
    {
      "id": "CP0033",
      "customer": "ユナイテッドシネマ",
      "name": "来期　水戸　シアター系統更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "小口",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": null,
      "orderJudge": "来期",
      "judgedAmountCurrent": null,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": null,
      "costRate": null,
      "expectedGrossProfit": null,
      "progress": "",
      "leader": "仮山口",
      "allocations": {}
    },
    {
      "id": "CP0034",
      "customer": "ユナイテッドシネマ",
      "name": "2026年UC各店保守契約",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 10000000,
      "orderJudge": "来期",
      "judgedAmountCurrent": 0,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": null,
      "costRate": null,
      "expectedGrossProfit": null,
      "progress": "",
      "leader": "山口",
      "allocations": {
        "小山": 0.15,
        "細萱": 0.15,
        "山口": 0.05,
        "金子": 0.4,
        "若山": 0.25
      }
    },
    {
      "id": "CP0035",
      "customer": "ユナイテッドシネマ",
      "name": "繰越　大津更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "小口",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": null,
      "orderJudge": "",
      "judgedAmountCurrent": null,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 0,
      "costRate": null,
      "expectedGrossProfit": 0,
      "progress": "積算中",
      "leader": "山口",
      "allocations": {}
    },
    {
      "id": "CP0036",
      "customer": "佐々木興業",
      "name": "三郷　GeM2導入（沼津移設）",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 8000000,
      "orderJudge": "-",
      "judgedAmountCurrent": 0,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 0,
      "costRate": null,
      "expectedGrossProfit": 0,
      "progress": "基本計画作成中",
      "leader": "小山",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.25,
        "山口": 0.05,
        "金子": 0.4,
        "若山": 0.05
      }
    },
    {
      "id": "CP0037",
      "customer": "佐々木興業",
      "name": "大和郡山　シアター系統更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2026-12-01",
      "completionTargetDate": "2027-06-01",
      "quoteAmountCurrent": 150000000,
      "orderJudge": "-",
      "judgedAmountCurrent": 0,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 0,
      "costRate": null,
      "expectedGrossProfit": 0,
      "progress": "基本計画作成中",
      "leader": "小山",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.25,
        "山口": 0.05,
        "金子": 0.4,
        "若山": 0.05
      }
    },
    {
      "id": "CP0038",
      "customer": "佐々木興業",
      "name": "各店保守　来期",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2026-04-01",
      "completionTargetDate": "2027-03-01",
      "quoteAmountCurrent": 6530000,
      "orderJudge": "△",
      "judgedAmountCurrent": 1959000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 1469250,
      "costRate": 0.75,
      "expectedGrossProfit": 489750,
      "progress": "見積作成中",
      "leader": "金子",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.25,
        "山口": 0.05,
        "金子": 0.4,
        "若山": 0.05
      }
    },
    {
      "id": "CP0039",
      "customer": "ニッパツ",
      "name": "厚生棟　空調更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "見積",
      "orderTargetDate": "2026-02-15",
      "completionTargetDate": "2027-01-15",
      "quoteAmountCurrent": 331700000,
      "orderJudge": "○",
      "judgedAmountCurrent": 199020000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 149265000,
      "costRate": 0.75,
      "expectedGrossProfit": 49755000,
      "progress": "見積作成中",
      "leader": "細萱",
      "allocations": {}
    },
    {
      "id": "CP0040",
      "customer": "山本さん",
      "name": "周南　AHUオーバーホール",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "受注",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 150000000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 150000000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 112500000,
      "costRate": 0.75,
      "expectedGrossProfit": 37500000,
      "progress": "竣工",
      "leader": "山本",
      "allocations": {
        "山本": 1
      }
    },
    {
      "id": "CP0041",
      "customer": "山本さん",
      "name": "柏の葉　GHP更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "見積",
      "orderTargetDate": "2026-06-01",
      "completionTargetDate": "2026-12-15",
      "quoteAmountCurrent": 200300000,
      "orderJudge": "-",
      "judgedAmountCurrent": 0,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": null,
      "costRate": null,
      "expectedGrossProfit": null,
      "progress": "工事計画書作成中",
      "leader": "山本",
      "allocations": {
        "山本": 1
      }
    },
    {
      "id": "CP0042",
      "customer": "山本さん",
      "name": "旬報社　冷温水発生機更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "受注",
      "orderTargetDate": "2026-04-01",
      "completionTargetDate": "2026-05-01",
      "quoteAmountCurrent": 40000000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 40000000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 30000000,
      "costRate": 0.75,
      "expectedGrossProfit": 10000000,
      "progress": "竣工",
      "leader": "山本",
      "allocations": {
        "山本": 1
      }
    },
    {
      "id": "CP0043",
      "customer": "山本さん",
      "name": "つくば　GHP更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "小口",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": null,
      "orderJudge": "-",
      "judgedAmountCurrent": null,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": null,
      "costRate": null,
      "expectedGrossProfit": null,
      "progress": "",
      "leader": "山本",
      "allocations": {
        "山本": 1
      }
    },
    {
      "id": "CP0044",
      "customer": "LED　PJ",
      "name": "109木場 LED更新工事",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "見積",
      "orderTargetDate": "2026-04-01",
      "completionTargetDate": "2026-10-01",
      "quoteAmountCurrent": 6900000,
      "orderJudge": "○",
      "judgedAmountCurrent": 4140000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 3105000,
      "costRate": 0.75,
      "expectedGrossProfit": 1035000,
      "progress": "着工前調整中",
      "leader": "若山",
      "allocations": {
        "小山": 0.1,
        "細萱": 0.1,
        "山口": 0.2,
        "金子": 0.05,
        "若山": 0.55
      }
    },
    {
      "id": "CP0045",
      "customer": "LED　PJ",
      "name": "109名古屋 LED更新工事",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2026-05-01",
      "completionTargetDate": "2026-11-01",
      "quoteAmountCurrent": 10600000,
      "orderJudge": "○",
      "judgedAmountCurrent": 6360000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 4770000,
      "costRate": 0.75,
      "expectedGrossProfit": 5830000,
      "progress": "着工前調整中",
      "leader": "若山",
      "allocations": {
        "小山": 0.1,
        "細萱": 0.1,
        "山口": 0.2,
        "金子": 0.05,
        "若山": 0.55
      }
    },
    {
      "id": "CP0046",
      "customer": "LED　PJ",
      "name": "109川崎 LED更新工事",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "見積",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 9850000,
      "orderJudge": "来期",
      "judgedAmountCurrent": 0,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 0,
      "costRate": null,
      "expectedGrossProfit": 0,
      "progress": "見積提出済",
      "leader": "若山",
      "allocations": {
        "小山": 0.1,
        "細萱": 0.1,
        "山口": 0.2,
        "金子": 0.05,
        "若山": 0.55
      }
    },
    {
      "id": "CP0047",
      "customer": "LED　PJ",
      "name": "CPX　平塚LED更新工事",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2026-09-01",
      "completionTargetDate": "2027-03-01",
      "quoteAmountCurrent": 8500000,
      "orderJudge": "○",
      "judgedAmountCurrent": 5100000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 3825000,
      "costRate": 0.75,
      "expectedGrossProfit": 1275000,
      "progress": "見積提出済",
      "leader": "若山",
      "allocations": {}
    },
    {
      "id": "CP0048",
      "customer": "LED　PJ",
      "name": "佐々木興業",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 10250000,
      "orderJudge": "○",
      "judgedAmountCurrent": 6150000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 4612500,
      "costRate": 0.75,
      "expectedGrossProfit": 1537500,
      "progress": "見積提出済",
      "leader": "若山",
      "allocations": {}
    },
    {
      "id": "CP0049",
      "customer": "LED　PJ",
      "name": "コロナワールド",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 9000000,
      "orderJudge": "○",
      "judgedAmountCurrent": 5400000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 4050000,
      "costRate": 0.75,
      "expectedGrossProfit": 1350000,
      "progress": "見積提出済",
      "leader": "若山",
      "allocations": {}
    },
    {
      "id": "CP0050",
      "customer": "東急レクリエーション",
      "name": "繰越　各店保守",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 48934000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 48934000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 36700500,
      "costRate": 0.75,
      "expectedGrossProfit": 12233500,
      "progress": "",
      "leader": "山口",
      "allocations": {
        "山本": 0.05
      }
    },
    {
      "id": "CP0051",
      "customer": "東急レクリエーション",
      "name": "繰越　佐賀保守",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 12602000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 2600000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 1950000,
      "costRate": 0.75,
      "expectedGrossProfit": 650000,
      "progress": "",
      "leader": "",
      "allocations": {
        "山本": 0.05
      }
    },
    {
      "id": "CP0052",
      "customer": "東急レクリエーション",
      "name": "繰越　湘南保守",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 12602000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 12602000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 9451500,
      "costRate": 0.75,
      "expectedGrossProfit": 3150500,
      "progress": "",
      "leader": "",
      "allocations": {
        "山本": 0.05
      }
    },
    {
      "id": "CP0053",
      "customer": "東急レクリエーション",
      "name": "繰越　神戸更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 191800000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 191800000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 143850000,
      "costRate": 0.75,
      "expectedGrossProfit": 47950000,
      "progress": "",
      "leader": "細萱",
      "allocations": {}
    },
    {
      "id": "CP0054",
      "customer": "TOHOシネマズ",
      "name": "繰越　各店保守",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 18373500,
      "orderJudge": "決定",
      "judgedAmountCurrent": 18373500,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 13780125,
      "costRate": 0.75,
      "expectedGrossProfit": 4593375,
      "progress": "",
      "leader": "金子",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.25,
        "山口": 0.05,
        "金子": 0.4,
        "若山": 0.05
      }
    },
    {
      "id": "CP0055",
      "customer": "ユナイテッドシネマ",
      "name": "繰越　各店保守",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 7270000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 7270000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 5452500,
      "costRate": 0.75,
      "expectedGrossProfit": 1817500,
      "progress": "",
      "leader": "山口",
      "allocations": {
        "山本": 0.05
      }
    },
    {
      "id": "CP0056",
      "customer": "ユナイテッドシネマ",
      "name": "繰越　前橋保守",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 4075600,
      "orderJudge": "決定",
      "judgedAmountCurrent": 4075600,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 3056700,
      "costRate": 0.75,
      "expectedGrossProfit": 1018900,
      "progress": "",
      "leader": "山口",
      "allocations": {
        "山本": 0.05
      }
    },
    {
      "id": "CP0057",
      "customer": "ユナイテッドシネマ",
      "name": "繰越　大津更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 56000000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 56000000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 42000000,
      "costRate": 0.75,
      "expectedGrossProfit": 14000000,
      "progress": "",
      "leader": "山本",
      "allocations": {}
    },
    {
      "id": "CP0058",
      "customer": "ユナイテッドシネマ",
      "name": "繰越　新座更新",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": null,
      "completionTargetDate": null,
      "quoteAmountCurrent": 77000000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 77000000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 57750000,
      "costRate": 0.75,
      "expectedGrossProfit": 19250000,
      "progress": "",
      "leader": "細萱",
      "allocations": {}
    },
    {
      "id": "CP0059",
      "customer": "佐々木興業",
      "name": "繰越　保守",
      "inquiryDate": null,
      "submitDate": null,
      "quoteType": "納期確認",
      "caseStatus": "",
      "orderTargetDate": "2026-04-01",
      "completionTargetDate": "2027-03-01",
      "quoteAmountCurrent": 6530000,
      "orderJudge": "決定",
      "judgedAmountCurrent": 6530000,
      "quoteAmountNext": null,
      "orderJudgeNext": "",
      "judgedAmountNext": null,
      "materialOutsourcing": 4897500,
      "costRate": 0.75,
      "expectedGrossProfit": 1632500,
      "progress": "",
      "leader": "金子",
      "allocations": {
        "小山": 0.25,
        "細萱": 0.25,
        "山口": 0.05,
        "金子": 0.4,
        "若山": 0.05
      }
    }
  ],
  "settings": {
    "fiscalEndMonth": 9,
    "judgeProbs": {
      "決定": 1.0,
      "◎": 0.8,
      "○": 0.6,
      "△": 0.3,
      "来期": 0.0,
      "-": 0.0,
      "": 0.0
    },
    "progressStages": [
      "基本計画作成中",
      "見積作成中",
      "見積提出済",
      "積算中",
      "着工前調整中",
      "工事中",
      "竣工",
      "完成図書作成",
      "売上"
    ]
  }
};
